# Multi-stage build — keeps the final image small by discarding build tooling.
#
# Stage 1 (deps):    install production dependencies only
# Stage 2 (builder): full install + `npm run build`
# Stage 3 (runner):  copy standalone output, run as non-root user

FROM node:22-alpine AS deps
WORKDIR /app

# Copy lockfile first so this layer is cached unless deps change
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# -----------------------------------------------------------------------

FROM node:22-alpine AS builder
WORKDIR /app

# Need all deps (including devDeps) for the build
COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# NEXT_PUBLIC_* vars used at build time must be passed in here.
# Pass them as --build-arg when running `docker build`, or they default
# to empty strings. The app reads these from the compiled JS bundle so
# they must be baked in at build time.
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_REGISTRATIONS_ENABLED=true
ARG NEXT_PUBLIC_REGISTRATION_WHITELIST_ENABLED=false
ARG NEXT_PUBLIC_REGISTRATION_WHITELIST
ARG NEXT_PUBLIC_ENABLE_TEST_SNAPSHOTS=false
ARG NEXT_PUBLIC_ASSISTANT_AI_ENABLED=true

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_REGISTRATIONS_ENABLED=$NEXT_PUBLIC_REGISTRATIONS_ENABLED
ENV NEXT_PUBLIC_REGISTRATION_WHITELIST_ENABLED=$NEXT_PUBLIC_REGISTRATION_WHITELIST_ENABLED
ENV NEXT_PUBLIC_REGISTRATION_WHITELIST=$NEXT_PUBLIC_REGISTRATION_WHITELIST
ENV NEXT_PUBLIC_ENABLE_TEST_SNAPSHOTS=$NEXT_PUBLIC_ENABLE_TEST_SNAPSHOTS
ENV NEXT_PUBLIC_ASSISTANT_AI_ENABLED=$NEXT_PUBLIC_ASSISTANT_AI_ENABLED

RUN npm run build

# -----------------------------------------------------------------------

FROM ubuntu:24.04 AS runner
WORKDIR /app

ENV NODE_ENV=production
# Disable Next.js telemetry in production containers
ENV NEXT_TELEMETRY_DISABLED=1

# Install runtime utilities & certificates
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates tar && \
    rm -rf /var/lib/apt/lists/*

# Copy Node.js 22 runtime from official node image
COPY --from=node:22 /usr/local /usr/local

# Install official Scalable Capital CLI (sc) for automated broker sync
ARG SCALABLE_CLI_VERSION=v1.1.0
RUN set -eux; \
    ARCH=$(uname -m); \
    case "$ARCH" in \
      x86_64) SC_ARCH="x86_64" ;; \
      aarch64|arm64) SC_ARCH="aarch64" ;; \
      *) echo "Unsupported architecture: $ARCH" && exit 1 ;; \
    esac; \
    curl -fsSL "https://github.com/ScalableCapital/scalable-cli/releases/download/${SCALABLE_CLI_VERSION}/sc-${SCALABLE_CLI_VERSION}-linux-${SC_ARCH}-gnu.tar.gz" -o /tmp/sc.tar.gz; \
    tar -xzf /tmp/sc.tar.gz -C /usr/local/bin --strip-components=1 "sc-${SCALABLE_CLI_VERSION}-linux-${SC_ARCH}-gnu/sc"; \
    chmod 755 /usr/local/bin/sc; \
    rm -f /tmp/sc.tar.gz

# Run as non-root nextjs user
RUN groupadd --system --gid 1001 nodejs && \
    useradd --system --uid 1001 --gid 1001 -m nextjs

# Configure sc CLI for file-backed sessions in headless server environments
RUN mkdir -p /home/nextjs/.config/scalable-cli && \
    printf '[auth]\nsession_backend = "file"\n' > /home/nextjs/.config/scalable-cli/config.toml && \
    chown -R nextjs:nodejs /home/nextjs && \
    chmod 700 /home/nextjs/.config/scalable-cli && \
    chmod 600 /home/nextjs/.config/scalable-cli/config.toml

# Copy static assets and standalone server
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Ensure all files and directories have proper read and execute permissions for nextjs
RUN chmod -R a+rX /app

USER nextjs
ENV HOME=/home/nextjs
ENV XDG_CONFIG_HOME=/home/nextjs/.config

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is generated by `output: "standalone"` in next.config.ts
CMD ["node", "server.js"]
