# Multi-stage build — keeps the final image small by discarding build tooling.
#
# Stage 1 (deps):    install production dependencies only
# Stage 2 (builder): full install + `npm run build`
# Stage 3 (runner):  copy standalone output, run as non-root user

FROM node:22-alpine AS deps
WORKDIR /app

# Copy lockfile first so this layer is cached unless deps change
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# -----------------------------------------------------------------------

FROM node:22-alpine AS builder
WORKDIR /app

# Need all deps (including devDeps) for the build
COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# NEXT_PUBLIC_* vars used at build time must be passed in here.
# Pass them as --build-arg when running `docker build`, or they default
# to empty strings. The app reads these from the compiled JS bundle so
# they must be baked in at build time.
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_REGISTRATIONS_ENABLED=true
ARG NEXT_PUBLIC_REGISTRATION_WHITELIST_ENABLED=false
ARG NEXT_PUBLIC_REGISTRATION_WHITELIST
ARG NEXT_PUBLIC_ENABLE_TEST_SNAPSHOTS=false
ARG NEXT_PUBLIC_ASSISTANT_AI_ENABLED=true

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_REGISTRATIONS_ENABLED=$NEXT_PUBLIC_REGISTRATIONS_ENABLED
ENV NEXT_PUBLIC_REGISTRATION_WHITELIST_ENABLED=$NEXT_PUBLIC_REGISTRATION_WHITELIST_ENABLED
ENV NEXT_PUBLIC_REGISTRATION_WHITELIST=$NEXT_PUBLIC_REGISTRATION_WHITELIST
ENV NEXT_PUBLIC_ENABLE_TEST_SNAPSHOTS=$NEXT_PUBLIC_ENABLE_TEST_SNAPSHOTS
ENV NEXT_PUBLIC_ASSISTANT_AI_ENABLED=$NEXT_PUBLIC_ASSISTANT_AI_ENABLED

RUN npm run build

# -----------------------------------------------------------------------

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
# Disable Next.js telemetry in production containers
ENV NEXT_TELEMETRY_DISABLED=1

# Run as non-root for security — the node image already has a `node` user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy static assets and standalone server in one layer
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Ensure all files and directories have proper read and execute permissions for nextjs
RUN chmod -R a+rX /app

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is generated by `output: "standalone"` in next.config.ts
CMD ["node", "server.js"]
