import 'server-only';

import { adminDb } from '@/lib/firebase/admin';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { Dividend, DividendFormData } from '@/types/dividend';
import { convertMultipleToEur, getExchangeRateToEur } from './currencyConversionService';
import { removeUndefinedDeep as removeUndefinedFields } from '@/lib/utils/firestoreData';

const DIVIDENDS_COLLECTION = 'dividends';

/**
 * Get all dividends for a specific user
 * Sorted by payment date (most recent first)
 */
export async function getAllDividends(userId: string): Promise<Dividend[]> {
  try {
    console.log('[dividendService] getAllDividends called for userId:', userId);
    const querySnapshot = await adminDb
      .collection(DIVIDENDS_COLLECTION)
      .where('userId', '==', userId)
      .orderBy('paymentDate', 'desc')
      .get();

    console.log('[dividendService] Query successful, docs count:', querySnapshot.size);

    const dividends = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data(),
      exDate: doc.data().exDate?.toDate() || new Date(),
      paymentDate: doc.data().paymentDate?.toDate() || new Date(),
      createdAt: doc.data().createdAt?.toDate() || new Date(),
      updatedAt: doc.data().updatedAt?.toDate() || new Date(),
    })) as Dividend[];

    console.log('[dividendService] Returning', dividends.length, 'dividends');
    return dividends;
  } catch (error) {
    console.error('[dividendService] Error getting dividends:', error);
    console.error('[dividendService] Error details:', {
      name: (error as Error).name,
      message: (error as Error).message,
      stack: (error as Error).stack,
    });
    throw error;
  }
}

/**
 * Get dividends for a specific asset
 * Sorted by payment date (most recent first)
 */
export async function getDividendsByAsset(
  userId: string,
  assetId: string
): Promise<Dividend[]> {
  try {
    const querySnapshot = await adminDb
      .collection(DIVIDENDS_COLLECTION)
      .where('userId', '==', userId)
      .where('assetId', '==', assetId)
      .orderBy('paymentDate', 'desc')
      .get();

    const dividends = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data(),
      exDate: doc.data().exDate?.toDate() || new Date(),
      paymentDate: doc.data().paymentDate?.toDate() || new Date(),
      createdAt: doc.data().createdAt?.toDate() || new Date(),
      updatedAt: doc.data().updatedAt?.toDate() || new Date(),
    })) as Dividend[];

    return dividends;
  } catch (error) {
    console.error('Error getting dividends by asset:', error);
    throw new Error('Failed to fetch dividends by asset');
  }
}

/**
 * Get dividends in a date range
 * Sorted by payment date (most recent first)
 */
export async function getDividendsByDateRange(
  userId: string,
  startDate: Date,
  endDate: Date
): Promise<Dividend[]> {
  try {
    const querySnapshot = await adminDb
      .collection(DIVIDENDS_COLLECTION)
      .where('userId', '==', userId)
      .where('paymentDate', '>=', Timestamp.fromDate(startDate))
      .where('paymentDate', '<=', Timestamp.fromDate(endDate))
      .orderBy('paymentDate', 'desc')
      .get();

    const dividends = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data(),
      exDate: doc.data().exDate?.toDate() || new Date(),
      paymentDate: doc.data().paymentDate?.toDate() || new Date(),
      createdAt: doc.data().createdAt?.toDate() || new Date(),
      updatedAt: doc.data().updatedAt?.toDate() || new Date(),
    })) as Dividend[];

    return dividends;
  } catch (error) {
    console.error('Error getting dividends by date range:', error);
    throw new Error('Failed to fetch dividends by date range');
  }
}

/**
 * Get a single dividend by ID
 */
export async function getDividendById(dividendId: string): Promise<Dividend | null> {
  try {
    const dividendDoc = await adminDb
      .collection(DIVIDENDS_COLLECTION)
      .doc(dividendId)
      .get();

    if (!dividendDoc.exists) {
      return null;
    }

    return {
      id: dividendDoc.id,
      ...dividendDoc.data(),
      exDate: dividendDoc.data()?.exDate?.toDate() || new Date(),
      paymentDate: dividendDoc.data()?.paymentDate?.toDate() || new Date(),
      createdAt: dividendDoc.data()?.createdAt?.toDate() || new Date(),
      updatedAt: dividendDoc.data()?.updatedAt?.toDate() || new Date(),
    } as Dividend;
  } catch (error) {
    console.error('Error getting dividend:', error);
    throw new Error('Failed to fetch dividend');
  }
}

/**
 * Compute a deterministic Firestore document ID for auto-generated dividends.
 * Format: {assetId}_{YYYY-MM-DD}_{dividendType}
 *
 * Using a deterministic ID makes concurrent writes idempotent: if the cron job
 * fires twice simultaneously, both writes target the same document ID and
 * last-write-wins produces exactly one document instead of two duplicates.
 *
 * Only used for isAutoGenerated=true dividends. Manual dividends use .add() (random ID).
 */
function buildDeterministicDividendId(assetId: string, exDate: Date, dividendType: string): string {
  const dateStr = exDate.toISOString().slice(0, 10); // "YYYY-MM-DD"
  return `${assetId}_${dateStr}_${dividendType}`;
}

/**
 * Create a new dividend
 *
 * Features:
 * - Automatically calculates netAmount if not provided (user convenience, avoids manual calculation errors)
 * - Converts amounts to EUR if currency is different (enables multi-currency portfolio analysis in EUR base)
 * - Continues without conversion on error (graceful degradation - better to save dividend without EUR data than fail completely)
 * - Auto-generated dividends use deterministic document IDs to prevent duplicates from concurrent cron runs
 *
 * @param userId - User ID
 * @param dividendData - Dividend form data
 * @param assetTicker - Asset ticker symbol
 * @param assetName - Asset display name
 * @param assetIsin - Optional ISIN code
 * @param isAutoGenerated - Whether dividend was auto-generated (e.g., from scraping)
 * @returns Created dividend ID
 */
export async function createDividend(
  userId: string,
  dividendData: DividendFormData,
  assetTicker: string,
  assetName: string,
  assetIsin?: string,
  isAutoGenerated: boolean = false
): Promise<string> {
  try {
    const now = new Date();

    // Auto-calculate netAmount if not already set
    // User convenience: avoid manual calculation errors (gross - tax = net)
    const netAmount = dividendData.netAmount || (dividendData.grossAmount - dividendData.taxAmount);

    // Convert dates to Date objects if they're strings
    const exDate = dividendData.exDate instanceof Date
      ? dividendData.exDate
      : new Date(dividendData.exDate);
    const paymentDate = dividendData.paymentDate instanceof Date
      ? dividendData.paymentDate
      : new Date(dividendData.paymentDate);

    // Currency conversion to EUR
    // Convert foreign currency dividends to EUR to enable unified multi-currency analysis
    // All stats, charts, and reports use EUR as the base currency
    let grossAmountEur: number | undefined;
    let taxAmountEur: number | undefined;
    let netAmountEur: number | undefined;
    let exchangeRate: number | undefined;

    if (dividendData.currency.toUpperCase() !== 'EUR') {
      try {
        // Get exchange rate
        exchangeRate = await getExchangeRateToEur(dividendData.currency);

        // Convert all amounts at once for efficiency
        const [convertedGross, convertedTax, convertedNet] = await convertMultipleToEur(
          [dividendData.grossAmount, dividendData.taxAmount, netAmount],
          dividendData.currency
        );

        grossAmountEur = convertedGross;
        taxAmountEur = convertedTax;
        netAmountEur = convertedNet;

        console.log(`[dividendService] Converted dividend from ${dividendData.currency} to EUR using rate ${exchangeRate}`);
      } catch (conversionError) {
        console.error('[dividendService] Currency conversion failed:', conversionError);
        // Graceful degradation: Continue without conversion - EUR fields remain undefined
        // Better to save dividend without EUR data than fail the entire operation
      }
    }

    const cleanedData = removeUndefinedFields({
      userId,
      assetId: dividendData.assetId,
      assetTicker,
      assetName,
      assetIsin,
      exDate: Timestamp.fromDate(exDate),
      paymentDate: Timestamp.fromDate(paymentDate),
      dividendPerShare: dividendData.dividendPerShare,
      quantity: dividendData.quantity,
      grossAmount: dividendData.grossAmount,
      taxAmount: dividendData.taxAmount,
      netAmount,
      currency: dividendData.currency,
      dividendType: dividendData.dividendType,
      notes: dividendData.notes,
      isAutoGenerated,
      // Provisional flag for inflation-linked coupons still awaiting their announced FOI rate.
      // Stripped by removeUndefinedFields for manual/equity dividends (always undefined there).
      isProvisional: dividendData.isProvisional,
      // Historical cost basis snapshot: asset.averageCost at time of dividend creation.
      // Undefined for dividends created before this field was introduced.
      costPerShare: dividendData.costPerShare,
      // Currency conversion fields (only if currency !== EUR)
      grossAmountEur,
      taxAmountEur,
      netAmountEur,
      exchangeRate,
      createdAt: now,
      updatedAt: now,
    });

    let docId: string;
    if (isAutoGenerated) {
      // Deterministic ID makes concurrent writes idempotent.
      // .set() on an existing doc is last-write-wins — safe since
      // concurrent writes produce identical data.
      docId = buildDeterministicDividendId(
        dividendData.assetId,
        exDate,
        dividendData.dividendType
      );
      await adminDb.collection(DIVIDENDS_COLLECTION).doc(docId).set(cleanedData);
    } else {
      // Manual dividends: preserve random ID behaviour
      const docRef = await adminDb.collection(DIVIDENDS_COLLECTION).add(cleanedData);
      docId = docRef.id;
    }

    return docId;
  } catch (error) {
    console.error('Error creating dividend:', error);
    throw new Error('Failed to create dividend');
  }
}

/**
 * Update an existing dividend
 * Recalculates EUR amounts if currency or amounts are changed
 */
export async function updateDividend(
  dividendId: string,
  // expenseId is not a form field: only the income sync writes it, to link (or unlink)
  // the expense row it created for this dividend. Passing the key with `undefined` is
  // the unlink — see the delete sentinel below; omitting the key leaves the link alone.
  updates: Partial<DividendFormData> & Pick<Dividend, 'expenseId'>
): Promise<void> {
  try {
    // Convert dates to Date objects if they're strings, then to Timestamps
    const exDate = updates.exDate
      ? (updates.exDate instanceof Date ? updates.exDate : new Date(updates.exDate))
      : undefined;
    const paymentDate = updates.paymentDate
      ? (updates.paymentDate instanceof Date ? updates.paymentDate : new Date(updates.paymentDate))
      : undefined;

    // Recalculate netAmount if gross or tax amounts changed
    let netAmount = updates.netAmount;
    if (updates.grossAmount !== undefined && updates.taxAmount !== undefined && !netAmount) {
      netAmount = updates.grossAmount - updates.taxAmount;
    }

    // Currency conversion to EUR (if currency is provided in updates)
    let grossAmountEur: number | undefined;
    let taxAmountEur: number | undefined;
    let netAmountEur: number | undefined;
    let exchangeRate: number | undefined;

    if (updates.currency && updates.currency.toUpperCase() !== 'EUR') {
      try {
        // Get exchange rate
        exchangeRate = await getExchangeRateToEur(updates.currency);

        // Determine which amounts to convert
        const amountsToConvert: number[] = [];
        if (updates.grossAmount !== undefined) amountsToConvert.push(updates.grossAmount);
        if (updates.taxAmount !== undefined) amountsToConvert.push(updates.taxAmount);
        if (netAmount !== undefined) amountsToConvert.push(netAmount);

        if (amountsToConvert.length > 0) {
          const convertedAmounts = await convertMultipleToEur(amountsToConvert, updates.currency);

          if (updates.grossAmount !== undefined) grossAmountEur = convertedAmounts.shift();
          if (updates.taxAmount !== undefined) taxAmountEur = convertedAmounts.shift();
          if (netAmount !== undefined) netAmountEur = convertedAmounts.shift();

          console.log(`[dividendService] Updated dividend with EUR conversion using rate ${exchangeRate}`);
        }
      } catch (conversionError) {
        console.error('[dividendService] Currency conversion failed during update:', conversionError);
      }
    } else if (updates.currency && updates.currency.toUpperCase() === 'EUR') {
      // If currency changed to EUR, clear conversion fields to avoid storing redundant data
      // EUR amounts don't need conversion (they ARE the base currency)
      grossAmountEur = undefined;
      taxAmountEur = undefined;
      netAmountEur = undefined;
      exchangeRate = undefined;
    }

    // A present-but-undefined `expenseId` is the unlink request. `removeUndefinedFields` would
    // drop the key and the stale link would survive the write, so it becomes the Admin delete
    // sentinel — a class instance the deep clean keeps. The `in` guard is what keeps a partial
    // caller (the PATCH route, a price refresh) that simply omits the field from wiping it.
    const expenseIdUpdate =
      'expenseId' in updates && updates.expenseId === undefined ? { expenseId: FieldValue.delete() } : {};

    const cleanedUpdates = removeUndefinedFields({
      ...updates,
      ...expenseIdUpdate,
      netAmount,
      exDate: exDate ? Timestamp.fromDate(exDate) : undefined,
      paymentDate: paymentDate ? Timestamp.fromDate(paymentDate) : undefined,
      grossAmountEur,
      taxAmountEur,
      netAmountEur,
      exchangeRate,
      updatedAt: new Date(),
    });

    await adminDb
      .collection(DIVIDENDS_COLLECTION)
      .doc(dividendId)
      .update(cleanedUpdates);
  } catch (error) {
    console.error('Error updating dividend:', error);
    throw new Error('Failed to update dividend');
  }
}

/**
 * Delete a dividend
 */
export async function deleteDividend(dividendId: string): Promise<void> {
  try {
    await adminDb
      .collection(DIVIDENDS_COLLECTION)
      .doc(dividendId)
      .delete();
  } catch (error) {
    console.error('Error deleting dividend:', error);
    throw new Error('Failed to delete dividend');
  }
}

/**
 * Check if a dividend already exists for an asset on a specific ex-date
 *
 * Uses same-day range logic (00:00:00 to 23:59:59) to match dividends with the same ex-date,
 * even if the exact timestamp differs slightly. This prevents duplicate imports from scraping.
 *
 * @param userId - User ID
 * @param assetId - Asset ID
 * @param exDate - Ex-dividend date to check
 * @returns True if duplicate exists, false otherwise
 */
export async function isDuplicateDividend(
  userId: string,
  assetId: string,
  exDate: Date
): Promise<boolean> {
  try {
    // Create date range for the same day (start of day to end of day)
    // This accounts for timezone differences and inexact timestamps from scrapers
    const startOfDay = new Date(exDate);
    startOfDay.setHours(0, 0, 0, 0);
    const endOfDay = new Date(exDate);
    endOfDay.setHours(23, 59, 59, 999);

    const querySnapshot = await adminDb
      .collection(DIVIDENDS_COLLECTION)
      .where('userId', '==', userId)
      .where('assetId', '==', assetId)
      .where('exDate', '>=', Timestamp.fromDate(startOfDay))
      .where('exDate', '<=', Timestamp.fromDate(endOfDay))
      .get();

    return !querySnapshot.empty;
  } catch (error) {
    console.error('Error checking duplicate dividend:', error);
    throw new Error('Failed to check duplicate dividend');
  }
}

/**
 * Delete all upcoming auto-generated coupon dividends for an asset.
 *
 * Used before generating a new next-coupon entry when bond details change
 * (e.g., rate update, quantity change, frequency change).
 *
 * Why: We store only the "next" coupon per bond. On any asset update,
 * we delete the old upcoming coupon and regenerate with new parameters.
 *
 * Side effect: any cashflow expense linked to a deleted coupon (expenseId) is
 * removed in the same batch, so re-saving a bond never leaves orphan expenses
 * behind (which would surface as duplicate "Dividendo …" entries in Cashflow).
 *
 * @param userId - User ID (security filter)
 * @param assetId - Asset ID to clean up coupons for
 */
export async function deleteUpcomingCouponsForAsset(
  userId: string,
  assetId: string
): Promise<void> {
  const now = new Date();
  now.setHours(0, 0, 0, 0);

  const querySnapshot = await adminDb
    .collection(DIVIDENDS_COLLECTION)
    .where('userId', '==', userId)
    .where('assetId', '==', assetId)
    .where('dividendType', '==', 'coupon')
    .where('isAutoGenerated', '==', true)
    .where('paymentDate', '>=', Timestamp.fromDate(now))
    .get();

  if (querySnapshot.empty) return;

  const batch = adminDb.batch();
  querySnapshot.docs.forEach(doc => {
    const expenseId = doc.data().expenseId as string | undefined;
    if (expenseId) {
      batch.delete(adminDb.collection('expenses').doc(expenseId));
    }
    batch.delete(doc.ref);
  });
  await batch.commit();
}

/**
 * Deletes all auto-generated finalPremium dividends for an asset.
 * Called before regenerating the final premium when bond details change.
 * No date filter: there is at most one finalPremium per asset.
 *
 * Side effect: any cashflow expense linked to a deleted premium (expenseId) is
 * removed in the same batch, mirroring deleteUpcomingCouponsForAsset.
 */
export async function deleteUpcomingFinalPremiumForAsset(
  userId: string,
  assetId: string
): Promise<void> {
  const querySnapshot = await adminDb
    .collection(DIVIDENDS_COLLECTION)
    .where('userId', '==', userId)
    .where('assetId', '==', assetId)
    .where('dividendType', '==', 'finalPremium')
    .where('isAutoGenerated', '==', true)
    .get();

  if (querySnapshot.empty) return;

  const batch = adminDb.batch();
  querySnapshot.docs.forEach(doc => {
    const expenseId = doc.data().expenseId as string | undefined;
    if (expenseId) {
      batch.delete(adminDb.collection('expenses').doc(expenseId));
    }
    batch.delete(doc.ref);
  });
  await batch.commit();
}
