import { adminDb } from '@/lib/firebase/admin';
import {
  createDividend,
  deleteUpcomingCouponsForAsset,
  deleteUpcomingFinalPremiumForAsset,
  getDividendById,
} from '@/lib/services/dividendService';
import { createExpenseFromDividend } from '@/lib/services/dividendIncomeService';
import { DividendFormData } from '@/types/dividend';
import { Asset } from '@/types/assets';
import { ExpenseCategory } from '@/types/expenses';

/** Where a user's dividends land in the cashflow (Impostazioni › Dividendi). */
export interface DividendIncomeCategory {
  categoryId: string;
  categoryName: string;
  subCategoryId?: string;
  subCategoryName?: string;
}

/**
 * The income category configured for dividends, or `undefined` when none is set (or it was
 * deleted). Read with the ADMIN SDK: a route has no signed-in client, so the client readers
 * (`getSettings`, `getCategoryById`) are refused by the rules there — the dividend PUT route used
 * them until 2026-09-20 and its `catch` swallowed the refusal, so an edited dividend never
 * reached its income row.
 */
export async function resolveDividendIncomeCategory(userId: string): Promise<DividendIncomeCategory | undefined> {
  const settingsDoc = await adminDb.collection('assetAllocationTargets').doc(userId).get();
  const settings = settingsDoc.exists ? settingsDoc.data() : null;
  if (!settings?.dividendIncomeCategoryId) return undefined;

  const categoryDoc = await adminDb.collection('expenseCategories').doc(settings.dividendIncomeCategoryId).get();
  if (!categoryDoc.exists) return undefined;

  const category = categoryDoc.data() as ExpenseCategory;
  const subCategory = settings.dividendIncomeSubCategoryId
    ? category.subCategories?.find((sub) => sub.id === settings.dividendIncomeSubCategoryId)
    : undefined;
  return {
    categoryId: settings.dividendIncomeCategoryId,
    categoryName: category.name,
    subCategoryId: settings.dividendIncomeSubCategoryId,
    subCategoryName: subCategory?.name,
  };
}

export type CreateDividendResult =
  | { skipped: true; reason: string }
  | { skipped: false; dividendId: string; expenseId?: string };

/**
 * Create a dividend entry with optional automatic expense creation.
 *
 * Orchestrates:
 *   1. Auto-generated coupon/finalPremium cleanup (prevents duplicate upcoming entries)
 *   2. costPerShare enrichment for accurate historical YOC
 *   3. Dividend creation via dividendService
 *   4. Conditional expense creation if paymentDate <= today and user has
 *      dividendIncomeCategoryId configured
 *
 * Returns { skipped: true } when an auto-generated entry for a sold asset
 * (quantity === 0) triggers cleanup but no new entry should be created.
 *
 * Ownership check (asset.userId === userId) must be performed by the caller
 * before invoking this function.
 */
export async function createDividendWithOptionalExpense(
  userId: string,
  dividendData: DividendFormData,
  asset: Asset & { id: string }
): Promise<CreateDividendResult> {
  // Cleanup stale auto-generated entries before creating a new one.
  // Prevents duplicate upcoming coupons when bond details are updated.
  if (dividendData.dividendType === 'coupon' && dividendData.isAutoGenerated) {
    await deleteUpcomingCouponsForAsset(userId, dividendData.assetId);
    // Asset sold: cleanup done, no new zero-amount entry needed
    if ((dividendData.quantity ?? 1) === 0) {
      return { skipped: true, reason: 'Upcoming coupons cleaned up; no new entry created (asset sold)' };
    }
  }
  if (dividendData.dividendType === 'finalPremium' && dividendData.isAutoGenerated) {
    await deleteUpcomingFinalPremiumForAsset(userId, dividendData.assetId);
    // Asset sold: cleanup done, no new zero-amount entry needed
    if ((dividendData.quantity ?? 1) === 0) {
      return { skipped: true, reason: 'Final premium cleaned up; no new entry created (asset sold)' };
    }
  }

  // Enrich with costPerShare snapshot for accurate historical YOC
  const enrichedDividendData: DividendFormData = {
    ...dividendData,
    costPerShare: asset.averageCost,
  };

  const dividendId = await createDividend(
    userId,
    enrichedDividendData,
    asset.ticker,
    asset.name,
    asset.isin,
    enrichedDividendData.isAutoGenerated
  );

  // ========== Conditional Expense Creation ==========
  //
  // Create expense immediately only for MANUAL dividends already paid
  // (paymentDate <= today), so historical entries the user adds by hand have an
  // immediate cashflow impact.
  //
  // Auto-generated coupons/finalPremiums are future-scheduled placeholders: their
  // cashflow expense must be created exclusively by the daily cron (Phase 2,
  // runExpenseCreation in dividendProcessor.ts) on the payment date. Creating it
  // here would (a) show a coupon as "received" before it actually is when the next
  // coupon date happens to be today, and (b) leak duplicate expenses on every bond
  // re-save, since cleanup regenerates the coupon each time.
  // Wrap in new Date() because paymentDate arrives as a JSON string from the client,
  // and string <= Date comparisons always return false in JavaScript.
  const paymentDate = new Date(dividendData.paymentDate);
  const today = new Date();
  today.setHours(23, 59, 59, 999);

  let expenseId: string | undefined;

  if (!dividendData.isAutoGenerated && paymentDate <= today) {
    expenseId = await createExpenseIfConfigured(userId, dividendId);
  }

  return { skipped: false, dividendId, expenseId };
}

/**
 * Create a cashflow expense for a dividend if the user has
 * dividendIncomeCategoryId configured in their settings.
 *
 * Non-fatal: returns undefined (and logs) if expense creation fails.
 * The dividend record is the primary operation; expense is secondary.
 */
async function createExpenseIfConfigured(
  userId: string,
  dividendId: string
): Promise<string | undefined> {
  try {
    const landing = await resolveDividendIncomeCategory(userId);
    if (!landing) return undefined;

    const dividend = await getDividendById(dividendId);
    if (!dividend) return undefined;

    return await createExpenseFromDividend(
      dividend,
      landing.categoryId,
      landing.categoryName,
      landing.subCategoryId,
      landing.subCategoryName
    );
  } catch (error) {
    // Non-critical: dividend creation already succeeded; expense is best-effort
    console.error('[createExpenseIfConfigured] Error creating expense from dividend:', error);
    return undefined;
  }
}
