/**
 * Budget status email (sent on Sundays).
 *
 * Server-only: imports firebase-admin and the Resend SDK. Reuses the same pure budget layer as
 * the in-app tab (`lib/utils/budgetUtils`) so the email and the page never disagree, and the
 * same narrative layer as the periodic emails (`lib/utils/emailNarrative`) so the words are
 * generated by rules and tested clause by clause.
 *
 * NOTHING in this email is weekly. It is SENT on Sunday; its figures are month-to-date,
 * year-to-date, or projected to month end. Every tile states its own window in its scope, and
 * the AI prompt is told the same thing in `buildCommentContext` — leaving the horizon implicit
 * produced a real error in production, a monthly ceiling reported as "a fine anno".
 *
 * Category budgets that actually exceeded their limit (ratio > 1) carry a per-expense
 * breakdown (with the note when present) so the reader sees *what* drove the overrun.
 */

import { adminDb } from '@/lib/firebase/admin';
import { Timestamp } from 'firebase-admin/firestore';
import { Resend } from 'resend';
import {
  escapeHtml,
  emailShell,
  emailVerdict,
  emailTile,
  emailHero,
  emailProse,
  emailBudgetRow,
  emailBudgetRows,
  emailBudgetTrack,
} from '@/lib/server/emailHtml';
import {
  buildBudgetEmailVerdict,
  describeOverallCeiling,
  describeMonthlyBudgetsTile,
  describeAnnualBudgetsTile,
  budgetWindowLabel,
} from '@/lib/utils/emailNarrative';
import { PRINT_COLORS, EMAIL_MONO_STACK } from '@/lib/constants/printTokens';
import { cachedFormatCurrencyEUR, formatPercentageIt } from '@/lib/utils/formatters';
import { getItalyDate, getItalyYear, getItalyMonth } from '@/lib/utils/dateHelpers';
import {
  getPeriodActual,
  getPeriodExpensesForItem,
  buildSpendingForecast,
  forecastMonthlyItem,
  splitMonthlyTotalExpenses,
  type CategoryTypeRef,
} from '@/lib/utils/budgetUtils';
import type { BudgetItem, BudgetPeriod } from '@/types/budget';
import type { Expense } from '@/types/expenses';
import { EMAIL_ANALYSIS_MODEL } from '@/lib/constants/aiModels';

const WARNING_RATIO = 0.8;

type BudgetRowStatus = 'ok' | 'warning' | 'over';

/** A single expense contributing to an over-budget category, for the email breakdown. */
interface OverspendExpense {
  description: string; // the note when present, otherwise the budget label
  subCategory?: string; // the expense's subcategory; omitted for subcategory-scoped budgets (redundant)
  date: Date;
  amount: number; // absolute EUR
}

interface WeeklyBudgetRow {
  label: string;
  period: BudgetPeriod;
  isIncome: boolean;
  spent: number;
  limit: number;
  ratio: number;
  projected: number | null; // end-of-month projection (monthly expense budgets only)
  status: BudgetRowStatus;
  // Individual expenses behind the overrun — populated only for category budgets that
  // actually exceeded their limit (ratio > 1). Never set for the overall budget.
  overspendExpenses?: OverspendExpense[];
}

export interface WeeklyBudgetData {
  rows: WeeklyBudgetRow[];
  overall: WeeklyBudgetRow | null;
  // Fraction of the year elapsed (0-100) — context for annual budgets
  yearElapsedPct: number;
  onTrackCount: number;
  atRiskCount: number;
  aiComment?: string;
  generatedAt: Date;
}

// ─── Date helper ────────────────────────────────────────────────────────────

/** True when `now`, in Italy timezone, falls on a Sunday. Exported for testing. */
export function isWeeklyBudgetDayItaly(now: Date): boolean {
  return getItalyDate(now).getDay() === 0;
}

// ─── Status ─────────────────────────────────────────────────────────────────

/**
 * Status for an expense budget row. Over when actuals (or, for monthly budgets,
 * the projection) exceed the limit; warning near the limit; otherwise ok.
 * Income targets are never "over" — reaching the target is good.
 */
function rowStatus(ratio: number, projectedRatio: number | null, isIncome: boolean): BudgetRowStatus {
  if (isIncome) return ratio >= 1 ? 'ok' : 'warning';
  if (ratio > 1 || (projectedRatio != null && projectedRatio > 1)) return 'over';
  if (ratio >= WARNING_RATIO) return 'warning';
  return 'ok';
}

// ─── Data builder ─────────────────────────────────────────────────────────────

/** Back-fills kind/period/amount for budget items saved before those fields existed. */
function normalizeItem(raw: BudgetItem & { monthlyAmount?: number }): BudgetItem {
  const kind =
    raw.kind === 'expense' || raw.kind === 'income'
      ? raw.kind
      : raw.scope === 'type' && raw.expenseType === 'income'
        ? 'income'
        : 'expense';
  return { ...raw, kind, period: raw.period ?? 'monthly', amount: raw.amount ?? raw.monthlyAmount ?? 0 };
}

function itemLabel(item: BudgetItem): string {
  if (item.scope === 'subcategory') return `${item.categoryName ?? ''} › ${item.subCategoryName ?? ''}`;
  return item.categoryName ?? item.expenseType ?? '';
}

/**
 * Builds the weekly budget status for a user. Returns null when the user has no
 * budgets configured (nothing to report).
 *
 * Fetches the year's expenses (annual budgets are year-to-date) and the user's
 * categories, whose type decides each budget's pace: a fixed or debt category is never
 * extrapolated by the day — the same rule the Budget tab applies (budgetUtils.resolveItemPace).
 */
export async function buildWeeklyBudgetData(userId: string, now: Date): Promise<WeeklyBudgetData | null> {
  const budgetSnap = await adminDb.collection('budgets').doc(userId).get();
  if (!budgetSnap.exists) return null;
  const data = budgetSnap.data() ?? {};

  const items = ((data.items ?? []) as Array<BudgetItem & { monthlyAmount?: number }>).map(normalizeItem);
  const overallMonthlyAmount: number | undefined = data.overallMonthlyAmount;
  if (items.length === 0 && !overallMonthlyAmount) return null;

  const year = getItalyYear(now);
  const windowStart = new Date(year, 0, 1);
  const expensesSnap = await adminDb
    .collection('expenses')
    .where('userId', '==', userId)
    .where('date', '>=', Timestamp.fromDate(windowStart))
    .where('date', '<=', Timestamp.fromDate(now))
    .get();

  const expenses: Expense[] = expensesSnap.docs.map((doc) => {
    const e = doc.data();
    return { ...(e as Expense), date: e.date?.toDate ? e.date.toDate() : e.date };
  });

  const categoriesSnap = await adminDb.collection('expenseCategories').where('userId', '==', userId).get();
  const categories: CategoryTypeRef[] = categoriesSnap.docs.map((doc) => ({ id: doc.id, type: doc.data().type }));

  const rows: WeeklyBudgetRow[] = items
    .filter((item) => item.amount > 0)
    .map((item) => {
      const spent = getPeriodActual(item, expenses, now);
      const ratio = item.amount > 0 ? spent / item.amount : 0;
      let projected: number | null = null;
      if (item.period === 'monthly' && item.kind === 'expense') {
        projected = forecastMonthlyItem(item, expenses, now, categories).projectedTotal;
      }
      const projectedRatio = projected != null && item.amount > 0 ? projected / item.amount : null;
      const label = itemLabel(item);

      // List the contributing expenses only when an expense budget actually exceeded
      // its limit (ratio > 1) — "sforato" means real spending past the limit, not a
      // forecast-only overrun. Income targets and on-track rows carry no breakdown.
      let overspendExpenses: OverspendExpense[] | undefined;
      if (item.kind !== 'income' && ratio > 1) {
        overspendExpenses = getPeriodExpensesForItem(item, expenses, now).map((expense) => ({
          description: expense.notes?.trim() || label,
          // A subcategory-scoped budget already names the subcategory in its title — don't repeat it.
          subCategory: item.scope === 'subcategory' ? undefined : expense.subCategoryName,
          date: expense.date,
          amount: Math.abs(expense.amount),
        }));
      }

      return {
        label,
        period: item.period,
        isIncome: item.kind === 'income',
        spent,
        limit: item.amount,
        ratio,
        projected,
        status: rowStatus(ratio, projectedRatio, item.kind === 'income'),
        overspendExpenses,
      };
    })
    .sort((a, b) => b.ratio - a.ratio);

  // Overall ceiling — all month spending vs the monthly limit
  let overall: WeeklyBudgetRow | null = null;
  if (overallMonthlyAmount && overallMonthlyAmount > 0) {
    const split = splitMonthlyTotalExpenses(expenses, year, getItalyMonth(now), now);
    const forecast = buildSpendingForecast(split, overallMonthlyAmount, now);
    const spent = forecast.spentSoFar;
    const projected = forecast.projectedTotal;
    const ratio = spent / overallMonthlyAmount;
    overall = {
      label: 'Budget complessivo',
      period: 'monthly',
      isIncome: false,
      spent,
      limit: overallMonthlyAmount,
      ratio,
      projected,
      status: rowStatus(ratio, projected / overallMonthlyAmount, false),
    };
  }

  const expenseRows = rows.filter((r) => !r.isIncome);
  const atRiskCount = expenseRows.filter((r) => r.status === 'over' || r.status === 'warning').length;
  const onTrackCount = expenseRows.length - atRiskCount;

  const italy = getItalyDate(now);
  const startOfYear = new Date(italy.getFullYear(), 0, 1);
  const dayOfYear = Math.floor((italy.getTime() - startOfYear.getTime()) / 86_400_000) + 1;
  const daysInYear = (italy.getFullYear() % 4 === 0 && italy.getFullYear() % 100 !== 0) || italy.getFullYear() % 400 === 0 ? 366 : 365;

  return {
    rows,
    overall,
    yearElapsedPct: (dayOfYear / daysInYear) * 100,
    onTrackCount,
    atRiskCount,
    generatedAt: now,
  };
}

// ─── AI comment ───────────────────────────────────────────────────────────────

const monthNameFormatter = new Intl.DateTimeFormat('it-IT', { month: 'long' });

/**
 * Builds the budget-status block handed to the model.
 *
 * Every line must carry its own time window. The email is sent weekly, but NONE of
 * its numbers are weekly: monthly budgets and the overall ceiling are month-to-date,
 * annual budgets are year-to-date, and projections land at end of month. Leaving the
 * horizon implicit produced a real error in production — the model saw only the
 * "anno trascorso al N%" hint and reported the overall projection as "a fine anno"
 * when it is in fact a monthly ceiling projected to month end.
 *
 * Pure — exported for testing.
 */
export function buildCommentContext(data: WeeklyBudgetData): string {
  const italy = getItalyDate(data.generatedAt);
  const monthName = monthNameFormatter.format(italy);
  const dayOfMonth = italy.getDate();
  const daysInMonth = new Date(italy.getFullYear(), italy.getMonth() + 1, 0).getDate();

  const header = [
    `Oggi è il giorno ${dayOfMonth} di ${daysInMonth} del mese di ${monthName} ${italy.getFullYear()}.`,
    `L'anno è trascorso al ${Math.round(data.yearElapsedPct)}%.`,
  ].join(' ');

  const lines = [
    data.overall &&
      `Budget complessivo (tetto MENSILE su tutte le spese): speso ${Math.round(data.overall.spent)}€ dal 1° ${monthName} a oggi, su un limite di ${Math.round(data.overall.limit)}€ per questo mese (${Math.round(data.overall.ratio * 100)}%). Al ritmo attuale la proiezione A FINE MESE è ${Math.round(data.overall.projected ?? 0)}€.`,
    ...data.rows.map((row) => {
      const window =
        row.period === 'annual' ? 'da inizio anno a oggi' : `dal 1° ${monthName} a oggi`;
      const horizon = row.period === 'annual' ? 'per quest\'anno' : 'per questo mese';
      const kind = row.isIncome ? 'obiettivo di entrata' : 'budget di spesa';
      const projection =
        row.projected != null && !row.isIncome
          ? ` Proiezione A FINE MESE: ${Math.round(row.projected)}€.`
          : '';
      return `${row.label} (${kind} ${row.period === 'annual' ? 'ANNUALE' : 'MENSILE'}): ${Math.round(row.spent)}€ ${window}, su un limite di ${Math.round(row.limit)}€ ${horizon} (${Math.round(row.ratio * 100)}%).${projection}`;
    }),
  ].filter(Boolean);

  return `${header}\n\n${lines.join('\n')}`;
}

/**
 * Generates a short Italian comment (2 sentences: the most notable fact + one concrete
 * action) for the weekly email. Non-blocking: returns null on any failure or when no
 * API key is set.
 */
async function generateWeeklyBudgetComment(data: WeeklyBudgetData): Promise<string | null> {
  if (!process.env.ANTHROPIC_API_KEY) return null;
  try {
    const prompt = `Sei un assistente finanziario personale italiano. Questo è lo stato dei budget dell'utente:

${buildCommentContext(data)}

REGOLE
- Usa SOLO i numeri e gli orizzonti temporali indicati sopra: non inventare cifre né ricavarne di nuove.
- Rispetta l'orizzonte di ogni voce. I budget mensili e il budget complessivo si misurano sul MESE CORRENTE e le loro proiezioni sono A FINE MESE: non definirle mai "a fine anno". Solo i budget annuali riguardano l'anno.
- Nessun dato qui è settimanale: la mail arriva ogni settimana, ma i numeri no. Non parlare di "questa settimana".

Scrivi esattamente DUE frasi brevi in italiano, da leggere in un colpo d'occhio:
1. il fatto più rilevante — il budget più critico (vicino o oltre il limite) oppure, se è tutto in ordine, l'andamento positivo più significativo;
2. una singola azione concreta e specifica che l'utente può fare da qui a fine periodo.
Niente elenchi, saluti, premesse o titoli.`;

    const Anthropic = (await import('@anthropic-ai/sdk')).default;
    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const message = await anthropic.messages.create({
      model: EMAIL_ANALYSIS_MODEL,
      // Thinking counts toward max_tokens: a ceiling sized for two sentences alone leaves
      // adaptive thinking at `high` no room, and the reply comes back cut or empty.
      max_tokens: 4096,
      thinking: { type: 'adaptive' },
      output_config: { effort: 'high' },
      messages: [{ role: 'user', content: prompt }],
    });
    const text = message.content
      .map((block) => (block.type === 'text' ? block.text : ''))
      .join('')
      .trim();
    return text || null;
  } catch (error) {
    console.error('[weeklyBudgetEmail] AI comment generation failed:', error);
    return null;
  }
}

// ─── HTML ─────────────────────────────────────────────────────────────────────
//
// A verdict over tiles, like every other surface. The one rule this email adds to the shared
// vocabulary: NOTHING here is weekly. It is sent on Sunday, and every figure in it is
// month-to-date, year-to-date or a projection to month end — so each tile states its own window
// in its scope, and the word "settimana" appears only once, in the footer, to say exactly that.

function formatEur(amount: number): string {
  return cachedFormatCurrencyEUR(amount, true);
}

/** The colour a row's fill takes. An income target is never "over": reaching it is the point. */
function statusHex(status: BudgetRowStatus): string {
  if (status === 'over') return PRINT_COLORS.negative;
  if (status === 'warning') return PRINT_COLORS.warning;
  return PRINT_COLORS.positive;
}

/** The chip beside a label — present only when the row needs attention. */
function statusScope(row: WeeklyBudgetRow): { scope?: string; scopeLevel?: 'exceeded' | 'warning' } {
  if (row.isIncome) return {};
  if (row.status === 'over') return { scope: 'superato', scopeLevel: 'exceeded' };
  if (row.status === 'warning') return { scope: 'vicino al limite', scopeLevel: 'warning' };
  return {};
}

const dayMonthFormatter = new Intl.DateTimeFormat('it-IT', { day: '2-digit', month: '2-digit' });

/**
 * The expenses behind an over-budget category, indented under its row.
 *
 * This is the one place the email answers "why" without an AI sentence: a category that
 * overshot by 60 € is a different problem depending on whether it was one purchase or twenty.
 */
function overspendHtml(expenses: OverspendExpense[]): string {
  const items = expenses
    .map((expense) => {
      const subCategory = expense.subCategory ? `${escapeHtml(expense.subCategory)} · ` : '';
      return `<tr>
                        <td width="44" style="padding:3px 0;font-size:11px;color:${PRINT_COLORS.mutedForeground};font-family:${EMAIL_MONO_STACK};white-space:nowrap;">${dayMonthFormatter.format(expense.date)}</td>
                        <td style="padding:3px 8px;font-size:11px;color:${PRINT_COLORS.mutedForeground};">${subCategory}${escapeHtml(expense.description)}</td>
                        <td align="right" style="padding:3px 0;font-size:11px;color:${PRINT_COLORS.mutedForeground};font-family:${EMAIL_MONO_STACK};white-space:nowrap;">${formatEur(expense.amount)}</td>
                      </tr>`;
    })
    .join('\n');

  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top:8px;border-left:2px solid ${PRINT_COLORS.border};border-collapse:collapse;">
                      <tr><td style="padding-left:11px;">
                        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
${items}
                        </table>
                      </td></tr>
                    </table>`;
}

/** One budget row: the figures, the track with today's mark on the row's OWN window. */
function budgetRowHtml(row: WeeklyBudgetRow, markPct: number | null, last: boolean): string {
  const pct = formatPercentageIt(row.ratio * 100, 0);
  const figures = `${escapeHtml(formatEur(row.spent))} / ${escapeHtml(formatEur(row.limit))} · <span style="color:${statusHex(row.status)};font-weight:600;">${escapeHtml(pct)}</span>`;

  // Spell out the horizon: "proiezione €X" alone was read as a year-end figure in production.
  const note =
    row.projected != null && !row.isIncome
      ? `proiezione a fine mese ${formatEur(row.projected)}`
      : row.isIncome
        ? 'un obiettivo di entrata non ha proiezione: o è arrivato, o non è arrivato'
        : undefined;

  return emailBudgetRow({
    label: row.label,
    ...statusScope(row),
    figures,
    usedPct: Math.min(100, row.ratio * 100),
    markPct,
    hex: statusHex(row.status),
    note,
    breakdown: row.overspendExpenses?.length ? overspendHtml(row.overspendExpenses) : undefined,
    last,
  });
}

/** Renders the weekly budget email. Inline styles and literal hex are what email clients need. */
export function buildWeeklyBudgetEmailHtml(data: WeeklyBudgetData): string {
  const italy = getItalyDate(data.generatedAt);
  const dayOfMonth = italy.getDate();
  const daysInMonth = new Date(italy.getFullYear(), italy.getMonth() + 1, 0).getDate();
  const monthName = monthNameFormatter.format(italy);
  const monthMark = (dayOfMonth / daysInMonth) * 100;

  const expenseRows = data.rows.filter((row) => !row.isIncome);
  const monthlyExpenses = expenseRows.filter((row) => row.period === 'monthly');
  const annualExpenses = expenseRows.filter((row) => row.period === 'annual');
  const incomeTargets = data.rows.filter((row) => row.isIncome);
  const exceededCount = expenseRows.filter((row) => row.status === 'over').length;

  const summaries = (rows: WeeklyBudgetRow[]) =>
    rows.map((row) => ({ label: row.label, ratio: row.ratio, status: row.status, isIncome: row.isIncome }));

  const verdict = buildBudgetEmailVerdict({
    onTrackCount: data.onTrackCount,
    atRiskCount: data.atRiskCount,
    exceededCount,
    overall: data.overall
      ? { spent: data.overall.spent, limit: data.overall.limit, projected: data.overall.projected }
      : null,
    dayOfMonth,
    daysInMonth,
  });

  const dateLabel = new Intl.DateTimeFormat('it-IT', { day: 'numeric', month: 'long', year: 'numeric' }).format(
    data.generatedAt,
  );

  const tiles: string[] = [
    emailVerdict({ eyebrow: 'Net Worth Tracker · Stato dei budget', scope: dateLabel, verdict }),
  ];

  if (data.aiComment) {
    tiles.push(
      emailTile({
        eyebrow: 'Commento AI',
        scope: `stato al ${dayOfMonth} ${monthName}`,
        body: emailProse(escapeHtml(data.aiComment)),
        footer: 'Generato da Assistente AI — verifica sempre le informazioni prima di agire.',
        muted: true,
      }),
    );
  }

  // ── The overall ceiling ──
  if (data.overall && data.overall.limit > 0) {
    const overall = data.overall;
    const projectionNote =
      overall.projected != null
        ? ` · proiezione a fine mese ${formatEur(overall.projected)} (${formatPercentageIt((overall.projected / overall.limit) * 100, 0)})`
        : '';
    tiles.push(
      emailTile({
        eyebrow: 'Tetto complessivo',
        scope: budgetWindowLabel('monthly', monthName),
        reading: describeOverallCeiling({
          spent: overall.spent,
          limit: overall.limit,
          dayOfMonth,
          daysInMonth,
        }),
        body:
          emailHero(formatEur(overall.spent)) +
          `\n            <div style="margin-top:2px;">${emailBudgetTrack(Math.min(100, (overall.spent / overall.limit) * 100), monthMark, statusHex(overall.status))}</div>` +
          `\n            <p style="margin:6px 0 0;font-family:${EMAIL_MONO_STACK};font-size:11px;color:${PRINT_COLORS.mutedForeground};">su ${escapeHtml(formatEur(overall.limit))}${escapeHtml(projectionNote)}</p>`,
        footer:
          'Il segno sulla traccia è il giorno di oggi sulla finestra del budget: il pieno oltre il segno significa che stai spendendo più in fretta del tempo che passa.',
      }),
    );
  }

  // ── Monthly expense budgets ──
  if (monthlyExpenses.length > 0) {
    tiles.push(
      emailTile({
        eyebrow: 'Budget mensili',
        scope: `${budgetWindowLabel('monthly', monthName)} · ${monthlyExpenses.length} voci`,
        reading: describeMonthlyBudgetsTile(summaries(monthlyExpenses)),
        body: emailBudgetRows(
          monthlyExpenses.map((row, index) => budgetRowHtml(row, monthMark, index === monthlyExpenses.length - 1)),
        ),
      }),
    );
  }

  // ── Annual expense budgets ──
  if (annualExpenses.length > 0) {
    tiles.push(
      emailTile({
        eyebrow: 'Budget annuali',
        scope: `${budgetWindowLabel('annual', monthName)} · anno al ${formatPercentageIt(data.yearElapsedPct, 0)}`,
        reading: describeAnnualBudgetsTile(summaries(annualExpenses), data.yearElapsedPct),
        body: emailBudgetRows(
          annualExpenses.map((row, index) =>
            budgetRowHtml(row, data.yearElapsedPct, index === annualExpenses.length - 1),
          ),
        ),
        footer:
          'Un budget annuale non ha proiezione a fine mese: la sua finestra è l’anno, e il segno sulla traccia è il giorno dell’anno.',
      }),
    );
  }

  // ── Income targets ──
  //
  // Their own tile, not a stray row among the expense budgets: "am I within my budgets?" and
  // "did what I expected arrive?" are two questions, and only the first has a limit to breach.
  if (incomeTargets.length > 0) {
    tiles.push(
      emailTile({
        eyebrow: 'Obiettivi di entrata',
        scope: budgetWindowLabel('monthly', monthName),
        body: emailBudgetRows(
          incomeTargets.map((row, index) =>
            budgetRowHtml(row, row.period === 'annual' ? data.yearElapsedPct : monthMark, index === incomeTargets.length - 1),
          ),
        ),
      }),
    );
  }

  return emailShell({
    title: 'Budget — stato',
    preheader: verdict.headline,
    body: tiles.join('\n'),
    footer:
      'Questa mail arriva ogni domenica, ma nessun importo è settimanale: ogni tessera dichiara la propria finestra.<br />Generato automaticamente da Net Worth Tracker',
  });
}

// ─── Send orchestrator ─────────────────────────────────────────────────────────

/**
 * Builds and sends the weekly budget email. Returns false when the user has no
 * budgets (email skipped). AI comment failure is non-blocking.
 */
export async function buildAndSendWeeklyBudget(
  userId: string,
  recipients: string[],
  now: Date = new Date()
): Promise<boolean> {
  const data = await buildWeeklyBudgetData(userId, now);
  if (!data) return false;

  const aiComment = await generateWeeklyBudgetComment(data);
  if (aiComment) data.aiComment = aiComment;

  const resend = new Resend(process.env.RESEND_API_KEY);
  const { error } = await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL ?? 'noreply@example.com',
    to: recipients,
    subject: 'Budget — riepilogo settimanale · Net Worth Tracker',
    html: buildWeeklyBudgetEmailHtml(data),
  });
  if (error) throw new Error(`Resend error: ${error.message}`);
  return true;
}
