'use client';

import { useState, useEffect, useRef } from 'react';
import { ResponsiveModal } from '@/components/ui/responsive-modal';
import { TILE_EYEBROW_CLASS, TILE_SUB_EYEBROW_CLASS } from '@/components/ui/tile';
import { NarrativeText } from '@/components/ui/narrative-text';
import { Button } from '@/components/ui/button';
import { Loader2, Copy, Check } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { format } from 'date-fns';
import { it } from 'date-fns/locale';
import { cachedFormatCurrencyEUR, formatTimePeriodLabel } from '@/lib/utils/formatters';
import {
  describeAnalysisBase,
  describeReturnMetrics,
  describeRisk,
  describeYields,
} from '@/lib/utils/performanceNarrative';
import { describeModalStatus, describeWriteError, type ModalStatus } from '@/lib/utils/dialogNarrative';
import { PERFORMANCE_ANALYSIS_MODEL } from '@/lib/constants/aiModels';
import { cn } from '@/lib/utils';
import { authenticatedFetch } from '@/lib/utils/authFetch';
import { toast } from 'sonner';
import type { PageVerdictModel, VerdictTone } from '@/lib/utils/narrative';
import type { PerformanceMetrics, TimePeriod } from '@/types/performance';

/**
 * AIAnalysisDialog — the AI report as a verdict over reading tiles (DESIGN.md → §5 Modal).
 *
 * The TITLE is the page's own verdict, generated by rules from the metrics on screen
 * (`buildPerformanceVerdict`, passed in by the page) — never the model's first sentence: two
 * runs on the same numbers would open with two different judgements, and a verdict slot that
 * changes under a fixed set of figures is not a verdict. The model's prose is the body of the
 * last block, labelled as what it is.
 *
 * Streaming: while the stream is open the text renders as plain `whitespace-pre-wrap` to avoid
 * the layout jumps ReactMarkdown produces re-parsing partial markdown on every chunk; the
 * markdown renderer takes over once the stream closes.
 */

export interface AIAnalysisDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  metrics: PerformanceMetrics;
  /** The page's own verdict over these metrics — the modal never builds a second one. */
  verdict: PageVerdictModel | null;
  timePeriod: TimePeriod;
  userId: string;
  triggerOrigin?: string;
  /**
   * The button that opened the dialog — the page writes `event.currentTarget` into this ref at the
   * click, where it already reads the rect for `triggerOrigin`. Without it the focus lands on
   * `body` after Escape (measured 2026-09-20, mouse and keyboard): a controlled Radix modal with
   * no `Dialog.Trigger` cancels the focus scope's own restore and focuses a trigger ref that is
   * null. The clicked element, not a lookup: `PageHeader` renders its actions twice and only one
   * copy is visible at a given width.
   */
  returnFocusTo?: React.RefObject<HTMLElement | null>;
}

const TONE_DOT_CLASS: Record<VerdictTone, string> = {
  positive: 'text-positive',
  neutral: 'text-muted-foreground',
  warning: 'text-warning-foreground',
  negative: 'text-destructive',
};

export function AIAnalysisDialog({
  open,
  onOpenChange,
  metrics,
  verdict,
  timePeriod,
  userId,
  triggerOrigin,
  returnFocusTo,
}: AIAnalysisDialogProps) {
  const [analysis, setAnalysis] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [status, setStatus] = useState<ModalStatus>({ phase: 'idle' });
  const [copied, setCopied] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<Date | null>(null);
  // The request in flight, if any. Closing the dialog aborts it (2026-09-20): until then the
  // stream ran to its end behind a closed modal — 8–14 s of paid generation nobody would read.
  // Only touched in handlers and effects, never during render.
  const requestRef = useRef<AbortController | null>(null);

  /**
   * Fetch AI analysis with streaming support (Server-Sent Events): `data: {JSON}\n\n` chunks
   * appended progressively, closed by `data: [DONE]`.
   */
  const fetchAnalysis = async () => {
    // A regenerate supersedes the request it replaces.
    requestRef.current?.abort();
    const request = new AbortController();
    requestRef.current = request;

    setLoading(true);
    setAnalysis('');
    setStatus({ phase: 'submitting' });

    try {
      const response = await authenticatedFetch('/api/ai/analyze-performance', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId, metrics, timePeriod }),
        signal: request.signal,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate analysis');
      }

      const reader = response.body?.getReader();
      const decoder = new TextDecoder();

      if (!reader) throw new Error('No response body');

      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });

        // Process complete SSE messages (delimited by \n\n)
        const lines = buffer.split('\n\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (!line.startsWith('data: ')) continue;
          const data = line.slice(6);

          if (data === '[DONE]') {
            setLoading(false);
            setGeneratedAt(new Date());
            setStatus({ phase: 'success' });
            return;
          }

          try {
            const parsed = JSON.parse(data);
            if (parsed.error) {
              setStatus({ phase: 'error', message: parsed.error });
              setLoading(false);
              return;
            }
            if (parsed.text) {
              setAnalysis((prev) => prev + parsed.text);
            }
          } catch (e) {
            console.warn('[AIAnalysisDialog] Failed to parse SSE chunk:', e);
          }
        }
      }

      setLoading(false);
      setStatus({ phase: 'success' });
    } catch (err) {
      if (request.signal.aborted) {
        // An abort is the reader's own choice, not a failure: no error reading, no toast. A newer
        // request owns the state by now if this one was superseded; otherwise the dialog was
        // closed, and a half-written report is dropped so the next opening starts a fresh one
        // instead of presenting a truncated text as the finished report.
        if (requestRef.current === request) {
          requestRef.current = null;
          setAnalysis('');
          setLoading(false);
          setStatus({ phase: 'idle' });
        }
        return;
      }
      setStatus({ phase: 'error', message: describeWriteError(err) });
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!open) return;
    // The cleanup runs on close AND on unmount: both abort the stream, client and server side
    // (the route forwards the abort to the Anthropic request). Aborting a settled request is a
    // no-op, so a finished report survives a close and is still there on reopen.
    const abortInFlight = () => requestRef.current?.abort();
    if (analysis || loading) return abortInFlight;
    // Deferred so the effect body itself sets no state (react-hooks/set-state-in-effect).
    const timer = setTimeout(() => {
      fetchAnalysis();
    }, 0);
    return () => {
      clearTimeout(timer);
      abortInFlight();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  const handleCopyAnalysis = async () => {
    if (!analysis) return;
    try {
      await navigator.clipboard.writeText(analysis);
      setCopied(true);
      toast.success('Analisi copiata negli appunti');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Impossibile copiare il testo');
    }
  };

  // The reading says where the report comes from and when — and, on failure, why there is none.
  const reading = describeModalStatus(status, {
    idle: [{ text: 'Sto per leggere i numeri del periodo.' }],
    submitting: 'Sto leggendo i numeri del periodo e scrivendo il report.',
    success: generatedAt
      ? `Report del ${format(generatedAt, 'd MMMM yyyy', { locale: it })} alle ${format(generatedAt, 'HH:mm', { locale: it })}, scritto da ${PERFORMANCE_ANALYSIS_MODEL}. Non è consulenza finanziaria.`
      : `Report scritto da ${PERFORMANCE_ANALYSIS_MODEL}. Non è consulenza finanziaria.`,
  });

  const footer = (
    <>
      {analysis && !loading && (
        <>
          <Button variant="outline" onClick={handleCopyAnalysis} className="gap-2">
            {copied ? (
              <>
                <Check className="h-4 w-4" aria-hidden="true" />
                Copiato
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" aria-hidden="true" />
                Copia il report
              </>
            )}
          </Button>
          <Button variant="outline" onClick={fetchAnalysis}>
            Rigenera
          </Button>
        </>
      )}
      <Button onClick={() => onOpenChange(false)}>Chiudi</Button>
    </>
  );

  return (
    <ResponsiveModal
      open={open}
      onClose={() => onOpenChange(false)}
      eyebrow={`Rendimenti · Analisi AI · ${formatTimePeriodLabel(timePeriod, metrics)}`}
      // The title IS the page's verdict, tone dot included — the one sentence that judges
      // these numbers, reused verbatim rather than re-phrased here (a second phrasing drifts).
      title={
        verdict ? (
          <>
            {verdict.headline.endsWith('.') ? verdict.headline.slice(0, -1) : verdict.headline}
            <span className={TONE_DOT_CLASS[verdict.tone]} aria-hidden="true">
              .
            </span>
          </>
        ) : (
          'Analisi del portafoglio'
        )
      }
      reading={reading}
      description={verdict ? verdict.headline : 'Analisi AI del portafoglio.'}
      width="xl"
      triggerOrigin={triggerOrigin}
      returnFocusTo={returnFocusTo}
      footer={footer}
    >
      <div className="space-y-4">
        {/* Reading tiles: one question each, the answer in words, then the figures. A metric
            that cannot be computed drops its row — never an "N/D" beside two real numbers. */}
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
          <ReadingTile
            eyebrow="Quanto ha reso"
            reading={
              <NarrativeText
                segments={describeReturnMetrics({
                  roi: metrics.roi,
                  cagr: metrics.cagr,
                  moneyWeightedReturn: metrics.moneyWeightedReturn,
                })}
                className="text-[13px] leading-[1.45] text-foreground"
              />
            }
            kpi={metrics.timeWeightedReturn}
            kpiFormat="percent"
            kpiCaption="TWR del periodo"
          />

          <ReadingTile
            eyebrow="Quanto è costato"
            reading={
              <NarrativeText
                segments={describeRisk({
                  volatility: metrics.volatility,
                  sharpeRatio: metrics.sharpeRatio,
                  monthsMeasured: metrics.numberOfMonths,
                })}
                className="text-[13px] leading-[1.45] text-foreground"
              />
            }
            kpi={metrics.maxDrawdown}
            kpiFormat="percent"
            kpiCaption="massimo drawdown"
          />

          <ReadingTile
            eyebrow="Su cosa è misurato"
            reading={
              <NarrativeText
                segments={describeAnalysisBase({
                  monthsMeasured: metrics.numberOfMonths,
                  netCashFlow: metrics.netCashFlow ?? null,
                })}
                className="text-[13px] leading-[1.45] text-foreground"
              />
            }
            kpi={metrics.endNetWorth}
            kpiFormat="euro"
            kpiCaption="patrimonio a fine periodo"
          />
        </div>

        {/* The yields row exists only where dividends were measured. */}
        {(() => {
          const yields = describeYields({
            yocNet: metrics.yocNet ?? null,
            currentYieldNet: metrics.currentYieldNet ?? null,
          });
          if (!yields) return null;
          return (
            <div className="rounded-xl bg-muted p-3.5">
              <p className={TILE_SUB_EYEBROW_CLASS}>Dividendi</p>
              <NarrativeText
                segments={yields}
                className="mt-1.5 text-[13px] leading-[1.45] text-foreground"
              />
            </div>
          );
        })()}

        <div>
          <div className="flex items-baseline justify-between gap-3">
            <p className={TILE_EYEBROW_CLASS}>Il report</p>
            <span className="text-[10px] text-muted-foreground">
              scritto dall&apos;assistente, non da una regola
            </span>
          </div>

          {loading && !analysis && (
            <div className="flex flex-col items-center justify-center gap-3 py-16">
              <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" aria-hidden="true" />
              <p className="text-sm text-muted-foreground">Analisi in corso…</p>
            </div>
          )}

          {/* Streaming: plain text to avoid ReactMarkdown re-parse jumps on partial markdown. */}
          {loading && analysis && (
            <p className="mt-2.5 max-w-[72ch] whitespace-pre-wrap text-sm leading-relaxed">
              {analysis}
            </p>
          )}

          {!loading && analysis && (
            <div className="prose prose-sm mt-2.5 max-w-[72ch] dark:prose-invert">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  strong: ({ children }) => (
                    <strong className="font-semibold text-foreground">{children}</strong>
                  ),
                  ul: ({ children }) => <ul className="list-inside list-disc space-y-1">{children}</ul>,
                  ol: ({ children }) => <ol className="list-inside list-decimal space-y-1">{children}</ol>,
                }}
              >
                {analysis}
              </ReactMarkdown>
            </div>
          )}

          {loading && analysis && (
            <div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground">
              <Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" />
              <span>Generazione in corso…</span>
            </div>
          )}
        </div>
      </div>
    </ResponsiveModal>
  );
}

/**
 * One reading tile inside the modal: eyebrow (the question), the answer in words, then the
 * figure. On the modal's `bg-card` surface a sub-tile is `bg-muted` — never `bg-card`, which
 * would be a card inside a card.
 */
function ReadingTile({
  eyebrow,
  reading,
  kpi,
  kpiFormat,
  kpiCaption,
}: {
  eyebrow: string;
  reading: React.ReactNode;
  kpi: number | null | undefined;
  kpiFormat: 'percent' | 'euro';
  kpiCaption: string;
}) {
  return (
    <section aria-label={eyebrow} className="flex min-w-0 flex-col rounded-xl bg-muted p-3.5">
      <p className={TILE_SUB_EYEBROW_CLASS}>{eyebrow}</p>
      <div className="mt-1.5">{reading}</div>
      {kpi !== null && kpi !== undefined && (
        <div className="mt-auto pt-3">
          <p
            className={cn(
              'font-mono text-[22px] font-bold leading-none tracking-[-0.025em] tabular-nums',
              kpiFormat === 'percent'
                ? kpi > 0
                  ? 'text-positive'
                  : kpi < 0
                    ? 'text-destructive'
                    : 'text-foreground'
                : 'text-foreground',
            )}
          >
            {kpiFormat === 'percent' ? formatSignedPercent(kpi) : cachedFormatCurrencyEUR(kpi, true)}
          </p>
          <p className="mt-1 text-[11px] text-muted-foreground">{kpiCaption}</p>
        </div>
      )}
    </section>
  );
}

/** it-IT percentage with an explicit sign and a typographic minus (The Comma Rule). */
function formatSignedPercent(value: number): string {
  const formatted = new Intl.NumberFormat('it-IT', {
    style: 'percent',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Math.abs(value) / 100);
  if (value > 0) return `+${formatted}`;
  if (value < 0) return `−${formatted}`;
  return formatted;
}
