import { describe, it, expect } from 'vitest';
import { Dividend } from '@/types/dividend';
import {
  netEur,
  grossEur,
  taxEur,
  isPaid,
  filterPaidByPeriod,
  monthsInWindow,
  computePeriodSummary,
  computeNetComparison,
  buildYearlySeries,
  computeReliability,
  rankPayerShares,
  summarizeYearlyIncome,
  nextPayments,
  summarizePayments,
  resolveMonthlyWindow,
  buildCoverageMonths,
  summarizeYield,
  summarizeDpsGrowth,
  summarizeTotalReturn,
  sliceForList,
  resolvePeriodBounds,
  summarizeDividendStats,
  selectUpcomingDividends,
  endOfServerDay,
} from '@/lib/utils/dividendAnalytics';

// --- Fixtures ---------------------------------------------------------------

// Minimal dividend factory. Payment date is the axis everything is grouped by; amounts
// default so that net = gross - tax. Dates are set at noon to stay clear of timezone
// boundaries in tests.
function makeDividend(overrides: Partial<Dividend> & { paymentDate: Date }): Dividend {
  const gross = overrides.grossAmount ?? 100;
  const tax = overrides.taxAmount ?? 26;
  return {
    id: Math.random().toString(36).slice(2),
    userId: 'u1',
    assetId: 'a1',
    assetTicker: 'AAA',
    assetName: 'Asset A',
    exDate: overrides.exDate ?? overrides.paymentDate,
    dividendPerShare: 1,
    quantity: 100,
    grossAmount: gross,
    taxAmount: tax,
    netAmount: gross - tax,
    currency: 'EUR',
    dividendType: 'ordinary',
    isAutoGenerated: false,
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2020-01-01'),
    ...overrides,
  };
}

const NOW = new Date('2026-06-15T12:00:00');

describe('money helpers', () => {
  it('prefers the converted EUR fields when present', () => {
    const d = makeDividend({
      paymentDate: new Date('2026-06-01T12:00:00'),
      grossAmount: 100,
      taxAmount: 15,
      netAmount: 85,
      grossAmountEur: 92,
      taxAmountEur: 13,
      netAmountEur: 79,
    });
    expect(grossEur(d)).toBe(92);
    expect(taxEur(d)).toBe(13);
    expect(netEur(d)).toBe(79);
  });

  it('falls back to native amounts for EUR/legacy records', () => {
    const d = makeDividend({ paymentDate: new Date('2026-06-01T12:00:00') });
    expect(netEur(d)).toBe(74); // 100 - 26
  });
});

describe('isPaid', () => {
  it('treats a payment on or before now as paid', () => {
    expect(isPaid(makeDividend({ paymentDate: new Date('2026-06-15T12:00:00') }), NOW)).toBe(true);
    expect(isPaid(makeDividend({ paymentDate: new Date('2026-06-10T12:00:00') }), NOW)).toBe(true);
  });

  it('treats a future payment as not paid', () => {
    expect(isPaid(makeDividend({ paymentDate: new Date('2026-07-01T12:00:00') }), NOW)).toBe(false);
  });
});

describe('filterPaidByPeriod', () => {
  const dividends = [
    makeDividend({ paymentDate: new Date('2026-06-05T12:00:00') }), // this month
    makeDividend({ paymentDate: new Date('2026-03-05T12:00:00') }), // this year, not month
    makeDividend({ paymentDate: new Date('2025-09-05T12:00:00') }), // within rolling12
    makeDividend({ paymentDate: new Date('2024-01-05T12:00:00') }), // old
    makeDividend({ paymentDate: new Date('2026-12-05T12:00:00') }), // future → excluded everywhere
  ];

  it('month keeps only the current calendar month', () => {
    expect(filterPaidByPeriod(dividends, 'month', NOW)).toHaveLength(1);
  });

  it('year keeps the current calendar year', () => {
    expect(filterPaidByPeriod(dividends, 'year', NOW)).toHaveLength(2);
  });

  it('rolling12 keeps the trailing 12 months', () => {
    // June 2026, March 2026, September 2025 are all within the last 12 months.
    expect(filterPaidByPeriod(dividends, 'rolling12', NOW)).toHaveLength(3);
  });

  it('all keeps every paid dividend (future excluded)', () => {
    expect(filterPaidByPeriod(dividends, 'all', NOW)).toHaveLength(4);
  });
});

describe('monthsInWindow', () => {
  it('returns 1 for month and 12 for rolling12', () => {
    expect(monthsInWindow('month', [], NOW)).toBe(1);
    expect(monthsInWindow('rolling12', [], NOW)).toBe(12);
  });

  it('returns elapsed months for year', () => {
    expect(monthsInWindow('year', [], NOW)).toBe(6); // June
  });

  it('spans first paid month → now for all', () => {
    const paid = [
      makeDividend({ paymentDate: new Date('2026-01-15T12:00:00') }),
      makeDividend({ paymentDate: new Date('2026-06-15T12:00:00') }),
    ];
    expect(monthsInWindow('all', paid, NOW)).toBe(6); // Jan..Jun inclusive
  });
});

describe('computePeriodSummary', () => {
  it('sums net/gross/tax and computes a true monthly average', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-02-15T12:00:00'), grossAmount: 120, taxAmount: 20, netAmount: 100 }),
      makeDividend({ paymentDate: new Date('2026-05-15T12:00:00'), grossAmount: 240, taxAmount: 40, netAmount: 200 }),
    ];
    const summary = computePeriodSummary(dividends, 'year', NOW);
    expect(summary.net).toBe(300);
    expect(summary.gross).toBe(360);
    expect(summary.tax).toBe(60);
    expect(summary.count).toBe(2);
    // 300 net over 6 elapsed months
    expect(summary.averageMonthlyNet).toBe(50);
  });
});

describe('computeNetComparison', () => {
  it('computes a signed delta vs the previous year', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), netAmount: 150, grossAmount: 150, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2025-03-15T12:00:00'), netAmount: 100, grossAmount: 100, taxAmount: 0 }),
    ];
    const cmp = computeNetComparison(dividends, 'year', NOW);
    expect(cmp.current).toBe(150);
    expect(cmp.previous).toBe(100);
    expect(cmp.deltaPct).toBeCloseTo(0.5);
  });

  it('returns null delta for all (no predecessor)', () => {
    const cmp = computeNetComparison([], 'all', NOW);
    expect(cmp.deltaPct).toBeNull();
  });

  it('returns null delta when the previous window had no income', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), netAmount: 150, grossAmount: 150, taxAmount: 0 }),
    ];
    expect(computeNetComparison(dividends, 'year', NOW).deltaPct).toBeNull();
  });
});


describe('buildYearlySeries', () => {
  it('groups gross/tax/net by payment year, ascending', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2025-03-15T12:00:00'), grossAmount: 100, taxAmount: 20, netAmount: 80 }),
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), grossAmount: 200, taxAmount: 40, netAmount: 160 }),
    ];
    const series = buildYearlySeries(dividends, NOW);
    expect(series.map((p) => p.year)).toEqual([2025, 2026]);
    expect(series[1]).toMatchObject({ gross: 200, tax: 40, net: 160 });
  });
});

describe('computeReliability', () => {
  it('measures income coverage across the window', () => {
    // 3 distinct months with income out of 6 elapsed this year → 50% coverage.
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-01-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
    ];
    const r = computeReliability(dividends, 'year', NOW);
    expect(r.monthsWithIncome).toBe(3);
    expect(r.monthsInWindow).toBe(6);
    expect(r.coveragePct).toBeCloseTo(0.5);
  });

  it('measures payer concentration (HHI and top share)', () => {
    const dividends = [
      makeDividend({ assetId: 'a', assetTicker: 'A', paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 75, grossAmount: 75, taxAmount: 0 }),
      makeDividend({ assetId: 'b', assetTicker: 'B', paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 25, grossAmount: 25, taxAmount: 0 }),
    ];
    const r = computeReliability(dividends, 'year', NOW);
    expect(r.topPayerSharePct).toBeCloseTo(0.75);
    expect(r.topPayerTicker).toBe('A');
    // HHI = 0.75^2 + 0.25^2 = 0.625
    expect(r.concentrationHhi).toBeCloseTo(0.625);
    expect(r.payerCount).toBe(2);
  });

  it('reports zero concentration when there is no income', () => {
    const r = computeReliability([], 'year', NOW);
    expect(r.topPayerSharePct).toBe(0);
    expect(r.concentrationHhi).toBe(0);
    expect(r.topPayerTicker).toBeNull();
  });

  it('measures only the instruments still held when given the set, on the period’s own window', () => {
    // Saipem (sold) paid the most in May; the BTP (held) paid in June. With the held set the
    // top payer is the BTP at 100% of the HELD income, over one month — but the window stays
    // the year’s six months, so the coverage is 1/6, not 1/1.
    const dividends = [
      makeDividend({ assetId: 'spm', assetTicker: 'SPM', paymentDate: new Date('2026-05-20T12:00:00'), netAmount: 142, grossAmount: 142, taxAmount: 0 }),
      makeDividend({ assetId: 'btp', assetTicker: 'BTP', paymentDate: new Date('2026-06-10T12:00:00'), netAmount: 57, grossAmount: 57, taxAmount: 0 }),
    ];
    const held = computeReliability(dividends, 'year', NOW, new Set(['btp']));
    expect(held.topPayerTicker).toBe('BTP');
    expect(held.topPayerSharePct).toBeCloseTo(1);
    expect(held.payerCount).toBe(1);
    expect(held.monthsWithIncome).toBe(1);
    expect(held.monthsInWindow).toBe(6);
    // Without the set the registry speaks: Saipem leads.
    expect(computeReliability(dividends, 'year', NOW).topPayerTicker).toBe('SPM');
    // An empty held set: nothing to count on, and the window is still the year’s.
    const none = computeReliability(dividends, 'year', NOW, new Set());
    expect(none.payerCount).toBe(0);
    expect(none.monthsInWindow).toBe(6);
  });
});


// ============================================================================
// The derivations the redesigned tab's tiles read (2026-08-23).
// ============================================================================

describe('rankPayerShares', () => {
  const payers = (n: number) =>
    Array.from({ length: n }, (_, i) =>
      makeDividend({
        paymentDate: new Date(2026, 2, 10, 12),
        assetId: `a${i}`,
        assetTicker: `T${i}`,
        assetName: `Asset ${i}`,
        grossAmount: (n - i) * 100,
        taxAmount: 0,
        netAmount: (n - i) * 100,
      })
    );

  it('ranks by net and shapes the rows like the category tiles', () => {
    const ranking = rankPayerShares(payers(3), 'year', NOW, 5);
    expect(ranking.total).toBe(600);
    expect(ranking.rows.map((r) => [r.label, r.amount])).toEqual([
      ['T0', 300],
      ['T1', 200],
      ['T2', 100],
    ]);
    expect(ranking.rows[0].percentage).toBeCloseTo(50, 5);
    expect(ranking.remainder).toBeNull();
    expect(ranking.payerCount).toBe(3);
    expect(ranking.top?.assetTicker).toBe('T0');
  });

  it('closes a cut list with the residual, so the shares add up to the stated total', () => {
    const ranking = rankPayerShares(payers(7), 'year', NOW, 5);
    expect(ranking.rows).toHaveLength(5);
    expect(ranking.remainder).not.toBeNull();
    expect(ranking.remainder!.label).toBe('Altri 2 strumenti');
    expect(ranking.remainder!.amount).toBe(300);
    const shown = ranking.rows.reduce((s, r) => s + r.amount, 0);
    expect(shown + ranking.remainder!.amount).toBe(ranking.total);
  });

  it('counts a payer once however many times it paid', () => {
    const list = [
      makeDividend({ paymentDate: new Date(2026, 1, 1, 12), assetId: 'x', assetTicker: 'X', grossAmount: 100, taxAmount: 0, netAmount: 100 }),
      makeDividend({ paymentDate: new Date(2026, 3, 1, 12), assetId: 'x', assetTicker: 'X', grossAmount: 50, taxAmount: 0, netAmount: 50 }),
    ];
    const ranking = rankPayerShares(list, 'year', NOW, 5);
    expect(ranking.payerCount).toBe(1);
    expect(ranking.top).toEqual(expect.objectContaining({ net: 150, count: 2 }));
  });

  it('excludes announced payments — a leaderboard of money not yet received is not a leaderboard', () => {
    const list = [
      makeDividend({ paymentDate: new Date(2026, 1, 1, 12), assetId: 'x', assetTicker: 'X', netAmount: 100, grossAmount: 100, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date(2026, 10, 1, 12), assetId: 'y', assetTicker: 'Y', netAmount: 900, grossAmount: 900, taxAmount: 0 }),
    ];
    expect(rankPayerShares(list, 'year', NOW, 5).payerCount).toBe(1);
  });

  it('is empty when nothing was received', () => {
    expect(rankPayerShares([], 'year', NOW, 5)).toEqual({
      rows: [],
      remainder: null,
      total: 0,
      payerCount: 0,
      heldPayerCount: 0,
      soldPayerCount: 0,
      soldNet: 0,
      top: null,
    });
  });

  it('ranks only the held payers and folds the sold ones into a named remainder, shares on the whole total', () => {
    // T0 (300) and T1 (200) sold, T2 (100) held: the one row is T2 at 100/600, the remainder
    // is «2 strumenti venduti» at 500 — the total still adds up and the top is the held one.
    const ranking = rankPayerShares(payers(3), 'year', NOW, 5, new Set(['a2']));
    expect(ranking.total).toBe(600);
    expect(ranking.rows.map((r) => [r.label, r.amount])).toEqual([['T2', 100]]);
    expect(ranking.rows[0].percentage).toBeCloseTo(100 / 6, 5);
    expect(ranking.remainder).toEqual({ label: '2 strumenti venduti', amount: 500, percentage: expect.closeTo(500 / 6, 5) });
    expect(ranking.payerCount).toBe(3);
    expect(ranking.heldPayerCount).toBe(1);
    expect(ranking.soldPayerCount).toBe(2);
    expect(ranking.soldNet).toBe(500);
    expect(ranking.top?.assetTicker).toBe('T2');
  });

  it('names a mixed remainder — beyond the cut AND sold — and has no top when everything was sold', () => {
    const mixed = rankPayerShares(payers(7), 'year', NOW, 2, new Set(['a0', 'a1', 'a2', 'a3']));
    expect(mixed.rows).toHaveLength(2);
    expect(mixed.remainder!.label).toBe('Altri 5 strumenti, 3 venduti');
    expect(mixed.remainder!.amount + mixed.rows.reduce((s, r) => s + r.amount, 0)).toBe(mixed.total);

    const allSold = rankPayerShares(payers(1), 'year', NOW, 5, new Set());
    expect(allSold.rows).toEqual([]);
    expect(allSold.top).toBeNull();
    expect(allSold.remainder).toEqual({ label: '1 strumento venduto', amount: 100, percentage: 100 });
  });
});

describe('summarizeYearlyIncome', () => {
  const yearly = (year: number, net: number) =>
    makeDividend({ paymentDate: new Date(year, 5, 1, 12), grossAmount: net, taxAmount: 0, netAmount: net });

  it('averages and ranks the CLOSED years only — a year still running would lose by construction', () => {
    const list = [yearly(2023, 1000), yearly(2024, 2000), yearly(2025, 3000), yearly(2026, 500)];
    const summary = summarizeYearlyIncome(list, NOW);
    expect(summary.closedCount).toBe(3);
    expect(summary.average).toBe(2000);
    expect(summary.best?.year).toBe(2025);
    expect(summary.worst?.year).toBe(2023);
    expect(summary.ongoing?.year).toBe(2026);
    expect(summary.ongoing?.net).toBe(500);
  });

  it('enumerates a gap-free year axis so a silent year reads as a zero, not as a missing bar', () => {
    const summary = summarizeYearlyIncome([yearly(2023, 1000), yearly(2026, 500)], NOW);
    expect(summary.years.map((y) => y.year)).toEqual([2023, 2024, 2025, 2026]);
    expect(summary.years[1].net).toBe(0);
  });

  it('keeps only the most recent years when the history is longer', () => {
    const list = [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026].map((y) => yearly(y, 100));
    const summary = summarizeYearlyIncome(list, NOW, 5);
    expect(summary.years.map((y) => y.year)).toEqual([2022, 2023, 2024, 2025, 2026]);
    expect(summary.closedCount).toBe(4);
  });

  it('has no average and no ranking when no year has closed', () => {
    const summary = summarizeYearlyIncome([yearly(2026, 500)], NOW);
    expect(summary.closedCount).toBe(0);
    expect(summary.average).toBeNull();
    expect(summary.best).toBeNull();
  });

  it('is empty without any received dividend', () => {
    expect(summarizeYearlyIncome([], NOW).years).toEqual([]);
  });
});

describe('nextPayments', () => {
  it('returns the announced payments in date order, soonest first', () => {
    const list = [
      makeDividend({ paymentDate: new Date(2026, 10, 20, 12), assetTicker: 'C', netAmount: 30, grossAmount: 30, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date(2026, 4, 20, 12), assetTicker: 'PAST', netAmount: 99, grossAmount: 99, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date(2026, 8, 15, 12), assetTicker: 'A', netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date(2026, 9, 28, 12), assetTicker: 'B', netAmount: 20, grossAmount: 20, taxAmount: 0 }),
    ];
    expect(nextPayments(list, NOW, 3).map((p) => p.assetTicker)).toEqual(['A', 'B', 'C']);
  });

  it('carries the provisional flag so the surface can say the figure is not final', () => {
    const list = [makeDividend({ paymentDate: new Date(2026, 10, 20, 12), isProvisional: true })];
    expect(nextPayments(list, NOW, 3)[0].isProvisional).toBe(true);
  });

  it('is empty when nothing is announced', () => {
    expect(nextPayments([makeDividend({ paymentDate: new Date(2026, 0, 1, 12) })], NOW, 3)).toEqual([]);
  });
});

describe('summarizePayments', () => {
  it('counts received and announced separately and never sums them', () => {
    const list = [
      makeDividend({ paymentDate: new Date(2026, 1, 1, 12), grossAmount: 100, taxAmount: 26, netAmount: 74 }),
      makeDividend({ paymentDate: new Date(2026, 2, 1, 12), grossAmount: 200, taxAmount: 52, netAmount: 148 }),
      makeDividend({ paymentDate: new Date(2026, 11, 1, 12), grossAmount: 400, taxAmount: 104, netAmount: 296 }),
    ];
    const inventory = summarizePayments(list, NOW);
    expect(inventory.total).toBe(3);
    expect(inventory.receivedCount).toBe(2);
    expect(inventory.receivedNet).toBe(222);
    expect(inventory.announcedCount).toBe(1);
    expect(inventory.announcedNet).toBe(296);
  });

  it('names the largest row across received AND announced — it is the inventory, not the income', () => {
    const list = [
      makeDividend({ paymentDate: new Date(2026, 1, 1, 12), assetTicker: 'SMALL', netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date(2026, 11, 1, 12), assetTicker: 'BIG', netAmount: 900, grossAmount: 900, taxAmount: 0, dividendType: 'coupon' }),
    ];
    expect(summarizePayments(list, NOW).largest).toEqual({ label: 'BIG', net: 900, dividendType: 'coupon' });
  });

  it('is empty for an empty list', () => {
    expect(summarizePayments([], NOW)).toEqual({
      total: 0,
      receivedCount: 0,
      receivedNet: 0,
      announcedCount: 0,
      announcedNet: 0,
      largest: null,
    });
  });
});

describe('resolveMonthlyWindow', () => {
  const list = [
    makeDividend({ paymentDate: new Date(2026, 0, 10, 12), netAmount: 100, grossAmount: 100, taxAmount: 0 }),
    makeDividend({ paymentDate: new Date(2026, 5, 10, 12), netAmount: 200, grossAmount: 200, taxAmount: 0 }),
  ];

  it('gives a month the trailing six, and outlines the month itself', () => {
    const w = resolveMonthlyWindow(list, 'month', NOW, 6);
    expect(w.points).toHaveLength(6);
    expect(w.points[5]).toEqual(expect.objectContaining({ year: 2026, month: 6 }));
    expect(w.highlightKey).toBe('2026-6');
  });

  it('gives a year its own months, January to the running one, and outlines none', () => {
    const w = resolveMonthlyWindow(list, 'year', NOW, 6);
    expect(w.points.map((p) => p.month)).toEqual([1, 2, 3, 4, 5, 6]);
    expect(w.highlightKey).toBeNull();
  });

  it('gives the trailing window and the whole history twelve months, named as such', () => {
    expect(resolveMonthlyWindow(list, 'rolling12', NOW, 6).points).toHaveLength(12);
    expect(resolveMonthlyWindow(list, 'all', NOW, 6).points).toHaveLength(12);
  });

  it('is gap-free: a month with no payment is a zero, not a missing bar', () => {
    const w = resolveMonthlyWindow(list, 'year', NOW, 6);
    expect(w.points.map((p) => p.net)).toEqual([100, 0, 0, 0, 0, 200]);
  });

  it('never draws an announced payment as income', () => {
    const w = resolveMonthlyWindow(
      [...list, makeDividend({ paymentDate: new Date(2026, 5, 30, 12), netAmount: 999, grossAmount: 999, taxAmount: 0 })],
      'year',
      new Date(2026, 5, 15, 12),
      6
    );
    expect(w.points[w.points.length - 1].net).toBe(200);
  });
});

describe('buildCoverageMonths', () => {
  const list = [
    makeDividend({ paymentDate: new Date(2026, 0, 10, 12), netAmount: 100, grossAmount: 100, taxAmount: 0 }),
    makeDividend({ paymentDate: new Date(2026, 2, 10, 12), netAmount: 200, grossAmount: 200, taxAmount: 0 }),
  ];

  it('marks each month of the window paid or not', () => {
    const months = buildCoverageMonths(list, 'year', NOW);
    expect(months.map((m) => m.month)).toEqual([1, 2, 3, 4, 5, 6]);
    expect(months.map((m) => m.paid)).toEqual([true, false, true, false, false, false]);
  });

  it('refuses to draw a window it cannot fit, rather than drawing a slice of it', () => {
    const old = makeDividend({ paymentDate: new Date(2020, 0, 10, 12), netAmount: 10, grossAmount: 10, taxAmount: 0 });
    expect(buildCoverageMonths([old, ...list], 'all', NOW, 24)).toEqual([]);
  });

  it('draws the whole history when it fits', () => {
    expect(buildCoverageMonths(list, 'rolling12', NOW, 24)).toHaveLength(12);
  });
});

describe('summarizeYield', () => {
  const payload = {
    portfolioYieldOnCost: 4.61,
    portfolioYieldOnCostNet: 3.59,
    portfolioCurrentYieldGross: 3.42,
    totalCostBasis: 124000,
    yieldOnCostAssets: [{ assetId: 'a', ttmGrossDividends: 5720 }],
    dividendGrowthData: { byAsset: [], portfolioMedianGrowth: 5.4 },
  };

  it('derives the spread and carries the base it was measured on', () => {
    const summary = summarizeYield(payload as never);
    expect(summary).not.toBeNull();
    expect(summary!.yocGross).toBe(4.61);
    expect(summary!.yocNet).toBe(3.59);
    expect(summary!.currentYieldGross).toBe(3.42);
    expect(summary!.spread).toBeCloseTo(1.19, 5);
    expect(summary!.dpsMedianGrowth).toBe(5.4);
    expect(summary!.ttmGross).toBe(5720);
    expect(summary!.costBasis).toBe(124000);
    expect(summary!.coverage).toBe(1);
  });

  it('has no spread when the market yield is missing — a spread against nothing is not a spread', () => {
    const summary = summarizeYield({ ...payload, portfolioCurrentYieldGross: undefined } as never);
    expect(summary!.currentYieldGross).toBeNull();
    expect(summary!.spread).toBeNull();
  });

  it('is null when the portfolio has no yield on cost at all', () => {
    expect(summarizeYield({ dividendGrowthData: { byAsset: [] } } as never)).toBeNull();
    expect(summarizeYield(null)).toBeNull();
  });
});

describe('summarizeDpsGrowth', () => {
  const payload = {
    dividendGrowthData: {
      portfolioMedianGrowth: 5.4,
      byAsset: [
        { assetId: 'a', assetTicker: 'ENI', assetName: 'Eni', currency: 'EUR', yearlyDps: [{ year: 2024, totalDps: 1 }, { year: 2025, totalDps: 1.1 }], yoyGrowth: {}, latestYoyGrowth: 7.4 },
        { assetId: 'b', assetTicker: 'ISP', assetName: 'Intesa', currency: 'EUR', yearlyDps: [{ year: 2025, totalDps: 0.17 }, { year: 2026, totalDps: 0.17 }], yoyGrowth: {}, latestYoyGrowth: 10.3 },
        { assetId: 'c', assetTicker: 'NEW', assetName: 'New', currency: 'EUR', yearlyDps: [{ year: 2026, totalDps: 0.1 }], yoyGrowth: {} },
      ],
    },
  };

  it('reads the table it sits above: the column set, the coverage and the leader', () => {
    const summary = summarizeDpsGrowth(payload as never, NOW);
    expect(summary!.coverage).toBe(3);
    expect(summary!.median).toBe(5.4);
    expect(summary!.years).toEqual([2024, 2025, 2026]);
    expect(summary!.best).toEqual({ assetTicker: 'ISP', latestYoyGrowth: 10.3 });
  });

  it('flags the running year among the columns, because its DPS is a partial sum', () => {
    expect(summarizeDpsGrowth(payload as never, NOW)!.ongoingYear).toBe(2026);
    expect(summarizeDpsGrowth(payload as never, new Date(2030, 0, 1, 12))!.ongoingYear).toBeNull();
  });

  it('is null without any DPS history', () => {
    expect(summarizeDpsGrowth({ dividendGrowthData: { byAsset: [] } } as never, NOW)).toBeNull();
    expect(summarizeDpsGrowth(null, NOW)).toBeNull();
  });
});

describe('summarizeTotalReturn', () => {
  const row = (assetTicker: string, totalReturnPercentage: number) => ({
    assetId: assetTicker,
    assetTicker,
    assetName: assetTicker,
    quantity: 1,
    averageCost: 1,
    currentPrice: 1,
    costBasis: 1,
    currentValue: 1,
    netDividends: 0,
    capitalGainAbsolute: 0,
    capitalGainPercentage: 0,
    dividendReturnPercentage: 0,
    totalReturnPercentage,
  });

  it('averages the rows unweighted and names both ends', () => {
    const summary = summarizeTotalReturn({ totalReturnAssets: [row('A', 60), row('B', 20), row('C', -10)] } as never);
    expect(summary!.count).toBe(3);
    expect(summary!.average).toBeCloseTo(23.333, 3);
    expect(summary!.best.assetTicker).toBe('A');
    expect(summary!.worst.assetTicker).toBe('C');
    expect(summary!.negativeCount).toBe(1);
  });

  it('is null with no rows', () => {
    expect(summarizeTotalReturn({ totalReturnAssets: [] } as never)).toBeNull();
    expect(summarizeTotalReturn(null)).toBeNull();
  });
});

describe('resolvePeriodBounds', () => {
  it('bounds a month to itself — the picker IS the month', () => {
    expect(resolvePeriodBounds('month', NOW)).toEqual({ from: { year: 2026, month: 6 }, to: { year: 2026, month: 6 } });
  });

  it('bounds a year to its whole calendar, December included', () => {
    expect(resolvePeriodBounds('year', NOW)).toEqual({ from: { year: 2026, month: 1 }, to: { year: 2026, month: 12 } });
  });

  it('bounds the trailing window to the twelve months ending on the running one', () => {
    expect(resolvePeriodBounds('rolling12', NOW)).toEqual({ from: { year: 2025, month: 7 }, to: { year: 2026, month: 6 } });
  });

  it('leaves the whole history unbounded — that is what «Storico» means', () => {
    expect(resolvePeriodBounds('all', NOW)).toEqual({ from: null, to: null });
  });
});

describe('sliceForList — announced payments are bounded too', () => {
  const received = makeDividend({ paymentDate: new Date(2026, 1, 1, 12), assetTicker: 'IN' });
  const laterThisMonth = makeDividend({ paymentDate: new Date(2026, 5, 28, 12), assetTicker: 'SOON' });
  const nextMonth = makeDividend({ paymentDate: new Date(2026, 6, 10, 12), assetTicker: 'NEXT' });
  const farFuture = makeDividend({ paymentDate: new Date(2032, 2, 10, 12), assetTicker: 'PREMIO' });
  const all = [received, laterThisMonth, nextMonth, farFuture];
  const tickers = (period: 'month' | 'year' | 'rolling12' | 'all') =>
    sliceForList(all, period, NOW).map((d) => d.assetTicker).sort();

  it('keeps a payment announced for LATER THIS MONTH under «Mese», and nothing beyond it', () => {
    // The bug this replaces: a final premium dated 2032 was listed under «agosto», because
    // every announced row was kept whatever the period.
    expect(tickers('month')).toEqual(['SOON']);
  });

  it('keeps everything falling inside the calendar YEAR, December included', () => {
    expect(tickers('year')).toEqual(['IN', 'NEXT', 'SOON']);
  });

  it('stops the trailing window at the end of the running month', () => {
    expect(tickers('rolling12')).toEqual(['IN', 'SOON']);
  });

  it('keeps the whole register under «Storico», the far-future premium included', () => {
    expect(tickers('all')).toEqual(['IN', 'NEXT', 'PREMIO', 'SOON']);
  });

  it('never drops a received payment the period covers', () => {
    expect(sliceForList([received], 'year', NOW)).toHaveLength(1);
  });
});

// --- The stats route's sums ----------------------------------------
//
// The route reads the collection once and derives three figures from it. The fixture holds the
// mirror's mix (2026-10-05): received and announced, a coupon, a payment in USD with EUR fields,
// a second instrument. Three falsifications were seen RED here: summing announced money into the
// received totals (the `<= endOfToday` gate dropped), the period's range ignored, and `now` not
// read by the upcoming selection (the same array at the end of the year).
describe('summarizeDividendStats / selectUpcomingDividends', () => {
  const at = (iso: string) => new Date(iso);
  const routeNow = at('2026-06-15T10:00:00.000Z');
  const list: Dividend[] = [
    makeDividend({ id: 'd3', assetId: 'eni', assetTicker: 'ENI.MI', paymentDate: at('2026-09-23T00:00:00Z'), grossAmount: 26, taxAmount: 6.76, dividendType: 'final' }),
    makeDividend({ id: 'd6', assetId: 'btp', assetTicker: 'BTP', paymentDate: at('2026-09-01T00:00:00Z'), grossAmount: 62.5, taxAmount: 7.8125, dividendType: 'coupon' }),
    makeDividend({ id: 'd4', assetId: 'aapl', assetTicker: 'AAPL', paymentDate: at('2026-06-15T00:00:00Z'), grossAmount: 2.6, taxAmount: 0.39, grossAmountEur: 2.4, netAmountEur: 2.04 }),
    makeDividend({ id: 'd5', assetId: 'btp', assetTicker: 'BTP', paymentDate: at('2026-03-01T00:00:00Z'), grossAmount: 62.5, taxAmount: 7.8125, dividendType: 'coupon' }),
    makeDividend({ id: 'd2', assetId: 'eni', assetTicker: 'ENI.MI', paymentDate: at('2025-11-19T00:00:00Z'), grossAmount: 26, taxAmount: 6.76, dividendType: 'interim' }),
    makeDividend({ id: 'd1', assetId: 'eni', assetTicker: 'ENI.MI', paymentDate: at('2025-05-21T00:00:00Z'), grossAmount: 25, taxAmount: 6.5 }),
  ];

  it('sums only what was RECEIVED: the two announced payments are never in the totals', () => {
    const stats = summarizeDividendStats(list, { now: routeNow });
    expect(stats.count).toBe(4);
    expect(stats.totalGross).toBeCloseTo(25 + 26 + 62.5 + 2.6, 10);
    expect(stats.byType.final.count, 'the announced final dividend').toBe(0);
    expect(stats.byType.coupon.count, 'the paid coupon only').toBe(1);
  });

  it('sums the NATIVE amounts, never the *Eur fields the tab reads (the route’s contract)', () => {
    const stats = summarizeDividendStats(list, { now: routeNow, assetId: 'aapl' });
    expect(stats.totalGross).toBe(2.6);
    expect(stats.byAsset.aapl).toMatchObject({ assetTicker: 'AAPL', totalGross: 2.6, count: 1 });
  });

  it('counts a payment dated today as received, whatever the hour of `now`', () => {
    const stats = summarizeDividendStats(list, { now: routeNow, assetId: 'aapl' });
    expect(stats.count).toBe(1);
    expect(selectUpcomingDividends(list, routeNow).map((d) => d.id)).not.toContain('d4');
  });

  it('honours the period range, inclusive at both ends, and an open bound', () => {
    const year2025 = summarizeDividendStats(list, { now: routeNow, startDate: at('2025-01-01T00:00:00Z'), endDate: at('2025-11-19T00:00:00Z') });
    expect(year2025.count).toBe(2);
    const from2026 = summarizeDividendStats(list, { now: routeNow, startDate: at('2026-01-01T00:00:00Z') });
    expect(Object.keys(from2026.byAsset).sort()).toEqual(['aapl', 'btp']);
  });

  it('selects the announced payments nearest first, ties by id like the Firestore query', () => {
    const tie = makeDividend({ id: 'd0', assetId: 'x', paymentDate: at('2026-09-01T00:00:00Z') });
    expect(selectUpcomingDividends([...list, tie], routeNow).map((d) => d.id)).toEqual(['d0', 'd6', 'd3']);
  });

  it('reads `now`: at the end of the year nothing of this list is upcoming any more', () => {
    expect(selectUpcomingDividends(list, routeNow)).toHaveLength(2);
    expect(selectUpcomingDividends(list, at('2026-12-31T12:00:00Z'))).toHaveLength(0);
    expect(summarizeDividendStats(list, { now: at('2026-12-31T12:00:00Z') }).count).toBe(6);
  });

  it('draws the end of today at 23:59:59.999 of the process day', () => {
    const end = endOfServerDay(routeNow);
    expect([end.getHours(), end.getMinutes(), end.getSeconds(), end.getMilliseconds()]).toEqual([23, 59, 59, 999]);
    expect(routeNow.getTime(), 'the input is not mutated').toBe(at('2026-06-15T10:00:00.000Z').getTime());
  });
});
